### ISSUE TITLE
Suggest adding strings to replace state messages

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#784] opened 2021-04-05 19:57 UTC
Suggest replacing these messages with strings:

Missing string when switching servers: vpn.controller.connectingState
Notifications screen: vpn.settings.unsecuredNetworkAlert, vpn.settings.unsecuredNetworkAlert.description, and vpn.settings.notificationVpnMustBeOff

Found by: cpeterson

**Comment by bakulf** [comment] 2021-04-06 13:02
Duplicate of https://github.com/mozilla-mobile/mozilla-vpn-client/issues/777

**Closed by bakulf** 2021-04-06 13:02 UTC
