### ISSUE TITLE
[foxfooding] When pressing the "Select location" field, the select location page is slow to be presented

### ISSUE THREAD

**Issue by pdehaan** [mozilla-mobile/mozilla-vpn-client#3701] opened 2022-06-07 00:43 UTC
When pressing the "Select location" field, the select location page is slow to be presented, as if it was waiting for data to be loaded before presenting the page. If that theory is true, data loading shouldn't affect the page presentation. Data should be loaded asynchronously and presented on the page when finished loading. Skeleton loading or spinner can be used on presented page if data isn't finished loading.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2374)

**Comment by pdehaan** [comment] 2022-06-07 20:56
https://user-images.githubusercontent.com/557895/172480848-0fc07930-03a9-41e1-b998-e4dab2d4846d.MP4

> It's hard to see in the video, but basically clicking on that cell isn't showing the new page instantly
>There's a delay before the click does anything
> Around a 1sec delay maybe? Or 0.8 sec :stuck_out_tongue: Hard to estimate

**Comment by bakulf** [comment] 2022-06-08 03:45
We don't fetch data when the location view is open, but yes we need to profile why this view is slow to render

**Comment by data-sync-user** [comment] 2023-07-07 15:56
➤ Adrienne Davenport commented:

Duplicate of VPN-5021

**Closed by data-sync-user** 2023-07-07 15:56 UTC
