### ISSUE TITLE
Support OpenSuSe

### ISSUE THREAD

**Issue by mcorino** [mozilla-mobile/mozilla-vpn-client#3749] opened 2022-06-13 18:18 UTC
Description
I managed to build mozillavpn on OpenSuSE Leap 15.4 without errors as far as I can tell and it works just fine as long as I stick to the commandline commands. Installation went fine and the mozillavpn.service runs ok.
When I attempt to start the UI though the app crashes with an abort message.

Technical Information
Platform: OpenSuSE Leap 15.4 (with Qt 6.3.0 installed)
FX product: Mozilla VPN 2.8.4

Steps to Reproduce

Turn on the computer
Click on the VPN menu item to open the app or use command line 'ui' command to start it, both fail.

Actual Results
When starting from the commandline the app terminates with the message "Aborted (core dumped)".

Journalctl shows:

Jun 13 19:51:18 mco-desktop.m2c-software.nl kernel: Code: ab f4 ff 48 8b 04 24 48 85 c0 74 07 8b 10 83 fa 01 7e 12 31 c9 31 d2 31 f6 4c 89 e7 e8 6c de fb ff 48 8b 04 24 48 8b 54 24 08 <4c> 8b 22 48 85 c0 74 06 f0 83 28 01 74 25 4d 85 e4 74 >
Jun 13 19:51:18 mco-desktop.m2c-software.nl kernel: mozillavpn[10802]: segfault at 0 ip 00000000004e12bd sp 00007fff3d2aa850 error 4 in mozillavpn[400000+5a6000]
Jun 13 19:51:18 mco-desktop.m2c-software.nl mozillavpn[10768]: [13.06.2022 19:51:18.471] Debug: (linux - DBusService) Version request
Jun 13 19:51:18 mco-desktop.m2c-software.nl systemd[1546]: Started MozillaVPN.
Jun 13 19:51:17 mco-desktop.m2c-software.nl plasmashell[1757]: file:///usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/RunnerResultsList.qml:50:9: Unable to assign [undefined] to int
Jun 13 19:51:17 mco-desktop.m2c-software.nl plasmashell[1757]: file:///usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/RunnerResultsList.qml:50:9: Unable to assign [undefined] to int
Jun 13 19:51:17 mco-desktop.m2c-software.nl plasmashell[1757]: file:///usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/RunnerResultsList.qml:50:9: Unable to assign [undefined] to int

Expected Results
The VPN should launch/open.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2403)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/VPN-2403

**Comment by birdsarah** [comment] 2022-06-16 17:09
Hi [mcorino](https://github.com/mcorino). Thanks for your report.

At the moment, unfortunately, OpenSuse is not a supported platform. 

We have lots of linux users on the team, including myself, so we understand how frustrating a response this is. 

We are not closing this ticket, we're just unlikely to get round to debugging this in the near future.

Based on your report it's probably something to do with Qt6. I recently found that I was able to build the vpn (on ubuntu) with no errors but then had runtime failures.

We have a separate ticket open here: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3730 to improve the readme and build instructions. The last comment from me describes what I had to do to get things working. I don't know how far this will get you on OpenSuse but would love to hear back from you if you're able to get any further.

**Comment by mcorino** [comment] 2022-06-16 17:41
Thanks for the reply.

As far as I can determine I have all the right (equivalent) packages installed (I checked several from control.qt6 list in detail) and as said I did not see any compile errors (only a small number of non-threatening warnings).

Can you elaborate about the dbus problems you mentioned in your comment. As the journalctl log shows the crash directly following a "Debug: (linux - DBusService) Version request" this might be relevant.

**Comment by Cimbali** [comment] 2022-08-01 17:56
I’m running into the same issue − segfault on UI start − when building the 2.9.0 release with Qt6, on OpenSUSE Tumbleweed.

I seem to always have a 1 or 2 threads in `runtime.futexsleep`, and the segfaulted thread with the following backtrace:
```
Stack trace of thread 27640:
#0  0x000000000050a158 QmlEngineHolder::window() const (mozillavpn + 0x10a158)
#1  0x000000000052dfdd SystemTrayNotificationHandler::SystemTrayNotificationHandler(QObject*) (mozillavpn + 0x12dfdd)
#2  0x000000000053bd76 LinuxSystemTrayNotificationHandler::LinuxSystemTrayNotificationHandler(QObject*) (mozillavpn + 0x13bd76)
#3  0x000000000050684a NotificationHandler::create(QObject*) (mozillavpn + 0x10684a)
#4  0x000000000048b1ab CommandUI::run(QList<QString>&)::{lambda()#1}::operator()() const (mozillavpn + 0x8b1ab)
#5  0x000000000047f577 std::function<int ()>::operator()() const (mozillavpn + 0x7f577)
#6  0x0000000000488c3c CommandUI::run(QList<QString>&) (mozillavpn + 0x88c3c)
#7  0x0000000000481132 CommandLineParser::parse(int, char**) (mozillavpn + 0x81132)
#8  0x0000000000440290 main (mozillavpn + 0x40290)
#9  0x00007fc2722ab5b0 __libc_start_call_main (libc.so.6 + 0x405b0)
#10 0x00007fc2722ab679 __libc_start_main_impl (libc.so.6 + 0x40679)
#11 0x0000000000443355 _start (mozillavpn + 0x43355)
```
`$_siginfo` is telling me the segfault is due to dereferencing a NULL pointer, but I don’t know if that’s 100% to be trusted. Nevertheless it’s the `window()` call on this line:

https://github.com/mozilla-mobile/mozilla-vpn-client/blob/3ae9aea3c262c0aa7a8d313976f80f38dcc957e5/src/systemtraynotificationhandler.cpp#L79-L80

**Comment by Cimbali** [comment] 2022-08-01 19:36
After rebuilding in debug mode and downloading all Qt6 debug symbols, it seems that `QmlEngineHolder::window()` happily takes the first value in the list of it’s `m_engine->rootObjects()` list.  However this list appears to be empty and uninitialised:

```
(gdb) frame 9
#9  QList<QObject*>::first (this=0x7fffffffc2e0) at /usr/include/qt6/QtCore/qlist.h:643
643         inline T& first() { Q_ASSERT(!isEmpty()); return *begin(); }
(gdb) p *this
$3 = {<QListSpecialMethods<QObject*>> = {<QListSpecialMethodsBase<QObject*>> = {<No data fields>}, <No data fields>}, d = {d = 0x0, ptr = 0x0, size = 0}}
```

In debug mode, the `!isEmpty()` assert inside `first()` (seen above) fails, called from here:

https://github.com/mozilla-mobile/mozilla-vpn-client/blob/77ad158acef4b1fb174de4252b0b95f1e18c1992/src/qmlengineholder.cpp#L52-L55

**Comment by Cimbali** [comment] 2022-08-01 21:21
I think the queued signal and `QGuiApplication::exit` only happen in the main loop, i.e. once `qApp->exec()` is called. However the window is needed before that, while the initialisation is still going on.

**Comment by JoeDotPHP** [comment] 2022-10-02 21:02
I'm also getting this on Pop!_OS 22.04 LTS.  Is it specifically for Ubuntu and not any downstream distros?

**Comment by data-sync-user** [comment] 2023-04-10 17:15
➤ Sarah Bird commented:

Santiago Andrigo marking this as enhancement as it’s effectively a request to support a new flavor of linux.

**Comment by data-sync-user** [comment] 2023-04-10 17:15
➤ Andrea Marchesini commented:

I assign this bug to me even if the PR was written by a contributor.

**Closed by data-sync-user** 2023-04-10 17:15 UTC

**Comment by Cimbali** [comment] 2023-04-11 08:27
This issue reported a crash when a runtime dependency was missing. I think this is reproducible from any platform where users

**Comment by Cimbali** [comment] 2023-04-11 11:34
For what it’s worth the [support page for Mozilla VPN on Linux](https://support.mozilla.org/en-US/kb/how-install-mozilla-vpn-linux-computer#w_other-linux-distributions) still says:

> **Note:** Mozilla VPN is available for:
>
> - Ubuntu 18.04 LTS (Bionic Beaver)
> -  Ubuntu 20.04 LTS (Focal Fossa)
> -  Ubuntu 22.04 LTS (Jammy Jellyfish)
>
> […]
>
> **Other Linux distributions**
>
> So far, we do not offer packages for any other Linux distributions.
