### ISSUE TITLE
VPN on MAC does not connect to the internet (restarting fixes it) 

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#2066] opened 2021-10-19 13:49 UTC
Description
Users cannot connect to VPN, it is stuck in "attempting to confirm connection" and turns off. After this the user no longer has internet connection on their device and has to reset their WiFi/ethernet to regain connection.

Technical Information

Platform: macOS 11.6
FX product Mozilla VPN 2.5

Steps to Reproduce

- Have an active VPN subscription
- Download/install VPN
- flip switch to connect to VPN

Actual Results
When tapping VPN switch it shows "attempting to confirm connection" and turns off a few seconds later. Internet connection is lost during the connection attempt and does not return after the VPN fails to connect

[mozillavpn-2021-10-19.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/7373799/mozillavpn-2021-10-19.txt)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1182)

**Comment by data-sync-user** [comment] 2022-04-05 15:21
➤ Betty Fleming commented:

Already in prod. Shouldn’t block release.

**Comment by data-sync-user** [comment] 2022-05-16 13:16
➤ Moritz Birghan commented:

I cannot reproduce!

Is this still an issue?

**Comment by data-sync-user** [comment] 2022-05-16 18:54
➤ Juan Zapata commented:

Moritz Birghan We haven’t had a confirmed case for a long time.

**Comment by data-sync-user** [comment] 2022-05-17 10:51
➤ Moritz Birghan commented:

Since there are no confirmed cases this might be fixed by a different change. 

Closing for now.

**Closed** 2022-05-17 10:51 UTC

**Comment by data-sync-user** [comment] 2022-05-23 11:24
➤ Bianca Hidecuti commented:

Verified this on Mozilla VPN 2.8.0/2.8.3/2.9.0, while on MacOS Big Sur 11.6, but we were not able to reproduce it.
