### ISSUE TITLE
spam

### ISSUE THREAD

**Issue by Mikksrund** [mozilla-mobile/mozilla-vpn-client#6961] opened 2023-05-22 12:27 UTC
https://vpn.mozilla.org/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-4841)

**Comment by lesleyjanenorton** [comment] 2023-05-22 15:35
hi @Mikksrund , was this a misfile? I'm going to close this because I can't tell what the issue is here.

**Closed as completed by lesleyjanenorton** 2023-05-22 15:35 UTC

**Comment by birdsarah** [comment] 2023-05-23 06:42
@lesleyjanenorton this looks like spam. This happens periodically on our repo. You can report to our sec team. And you can report to github and delete the issue.
