### ISSUE TITLE
[iOS] Switching locations is unreliable

### ISSUE THREAD

**Issue by martinbalfanz** [mozilla-mobile/mozilla-vpn-client#235] opened 2020-11-17 11:08 UTC
(Note: @chrismore pointed out that this bug may affect all platforms, not just iOS)

When switching locations, the VPN client usually does not properly connect for me. I have to disable and re-enable it to make it work.

STR:
- Open the VPN app and connect to a location
- Open a browser and verify that you are connected (e.g. by visiting `https://duckduckgo.com/?q=what%27s+my+IP&atb=v1-1&ia=answer`)
- Switch back to the VPN client and select a different location

ER:
- The VPN client should connect to the new location

AR: 
- The VPN client shows that it's connected, but when trying to verify it in a browser, the page doesn't load. Switching back to the VPN app shows the message "No signal". Disabling and re-enabling is required.

Please see the video attached, esp. the second half. (Sorry about the length. It's one recording to also show issue #234)

![RPReplay_Final1605525880 2020-11-17 12_08_08_02](https://user-images.githubusercontent.com/653763/99383001-98174280-28cd-11eb-976a-9edf87af4d9c.gif)

**Comment by chrismore** [comment] 2020-12-03 18:24
@martinbalfanz can you confirm if using the latest version of iOS if this is still happening?

@ValentinaPC can you review this and see if you can confirm the steps to reproduce above? thanks!

If we can confirm this is still happening, we may switch this to P0.

**Comment by ValentinaPC** [comment] 2020-12-04 13:46
We did tried to reproduce this way back, but did no manege to do in the mentioned format.
- I was unable to switch so quickly (while the locations switch) between pages.
- We've checked this while in a video call, and yes, we can confirm that for few seconds, the internet connections fails - but this is, if I understood correctly - expected.
- Also, there are regions that trigger the "no signal" state, while VPN is turned on. This happens intermittently, for all platforms and this too might seem normal. The good part is that the "No signal" state ends very quickly.

**Comment by bakulf** [comment] 2020-12-04 14:00
The new version of the code doesn't allow the user to load content during a server switch.
So I suspect this issue can be closed. Reopen it if you are able to reproduce it.

**Comment by martinbalfanz** [comment] 2020-12-07 12:51
I'm still able to reproduce this on iOS. Even worse, I managed to get [my IP leaked again](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/234). Please see the attached video.

1. shows my IP, VPN deactivted. Everything as expected
2. I activate the VPN in Helskini and inspect DDG => Note that my location says Russia. I have never selected Russia before
3. I switch to Denmark, and am still displayed in Russia.
4. I switch to the VPN app, to verify => I get "no Signal" and it doesn't go away by itself. Switching to DDG shows no connection. I didn't do anything in between, and doesn't matter how long I wait, it doesn't resolve itself.
5. Back to VPN app, I switch to Hong Kong. Then back to Focus to verify => my private IP is leaked

VPN version 2.0.0 (2.202012041134)


![RPReplay_Final1607344635 2020-12-07 13_44_43](https://user-images.githubusercontent.com/653763/101352961-2d857100-3893-11eb-8a19-0e02a682f90f.gif)

**Comment by ValentinaPC** [comment] 2020-12-07 15:25
Verified this on my Android 10 device, using the latest VPN cross plat beta build and things works as expected.
Verified this on my iOS 14.2 device, using the latest VPN cross-plat beta build and obtained the following:
- VPN turned off - IP address is correct;
- VPN turned on for Finland => IP address is Sofia (Bulgaria);
- VPN tuned on for Denmark => IP address is Copenhagen (Denmark)
- VPN turned on for Hong Kong => IP address is Hong Kong;

This is happening intermittently. Managed to reproduce twice.

**Comment by bakulf** [comment] 2020-12-10 18:00
I have enforced a better server-switching that should not trigger the instability issue.
The IP leak can be fixed in a separate commit.

**Comment by ValentinaPC** [comment] 2020-12-11 13:02
I've tried to reproduce the "IP leaking" issue while using the 1.0 VPN client build on my Android 10 device, and I was not able. 
The "locations" issue is also reproducible while using the 1.0 client.

**Comment by martinbalfanz** [comment] 2020-12-11 15:14
I can still reproduce both issues.

For the IP leak, it happens when you switch apps too fast. Here are my STRs:
- Open VPN app, sign-in etc.
- Connect to a location
- verify your IP, e.g. by using Firefox Focus
- switch to a different location
- before any UI updates or notifications, and while the connection is establishing, switch to Focus again and verify your IP

AR: personal IP address is shown
ER: there should be no connection until the VPN is connected

It may seem like an edge case, but when I switch to Hong Kong as a location I can perform the steps quite slowly and still run into the problem.

**Comment by chrismore** [comment] 2021-01-04 16:20
@bakulf can you provide some feedback on this issue?

@ValentinaPC are you still able to replicate on iOS?

> I can still reproduce the IP leak. It happens when you switch apps too fast. Here are my STRs:
> 
>     * Open VPN app, sign-in etc.
> 
>     * Connect to a location
> 
>     * verify your IP, e.g. by using Firefox Focus
> 
>     * switch to a different location
> 
>     * before any UI updates or notifications, and while the connection is establishing, switch to Focus again and verify your IP
> 
> 
> AR: personal IP address is shown
> ER: there should be no connection until the VPN is connected
> 
> It may seem like an edge case, but when I switch to Hong Kong as a location I can perform the steps quite slowly and still run into the problem.

Are you able to replicate it on iOS or Android or both?

**Comment by chrismore** [comment] 2021-01-08 16:33
@ValentinaPC ^^ 

Also, how often do you see this happen?

**Comment by ValentinaPC** [comment] 2021-01-11 09:17
Verified this on different platforms and obtained the following results:
**1. Mac OS 10.15.7 - VPN prod version 2.0.1**
- the location switch is made very quickly (even if the VPN app is hidden) and the IP Address page displays each time the correct IP.

**2. Android 10 - VPN beta version 2.0.1**
- the location switch is not made in background, but the IP Address page does not display the real IP address, but the previous location used address.

See video below.
![ezgif com-resize](https://user-images.githubusercontent.com/15685960/104162935-328f9000-53fe-11eb-90f9-a5894048f823.gif)

**3. iOS 14.2 - VPN prod version 2.0.1**
- the location switch is not made in background,  AND the IP Address page DISPLAYS user's real IP address.
- extra details: with VPN on, switch the location and hide the app as you navigate quickly to a IP Address page using your browser (I've used Safari).

See video below.
![ezgif com-resize(1)](https://user-images.githubusercontent.com/15685960/104163103-8306ed80-53fe-11eb-88bb-7e9e0bfcce68.gif)

**Comment by ValentinaPC** [comment] 2021-01-21 11:44
I've logged the background issue separately. ()
The iOS IP leak issue stays here. Issue described above. This is reproduced on iPad with iOS 14.2 and not on the iPhone with 13.1.2. - not sure why.
@chrismore

**Comment by mbirghan** [comment] 2021-04-28 15:24
We landed a patch to switch the server in 1 command instead of disconnecting and reconnecting. This should fix the issue and I was not able to reproduce it anymore on my machine.

**Closed** 2021-05-02 21:49 UTC
Labels: iOS, p1, qa_major

**Comment by ValentinaPC** [comment] 2021-05-14 07:16
Verified as fixed on iOS 14.4, using VPN client v. 2.3.0 (2.202105111308).
The location switch is made in background and the IP listed is the IP of the new location.
