### ISSUE TITLE
Small flicker for “Protect all apps with VPN” disabled button while accessing the App Permission screen

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1410] opened 2021-07-23 14:42 UTC
#### VPN version:
2.4.0 (2.202107230655)

#### Affected Platforms:
* Linux Ubuntu 20.04;

#### Prerequisites:
* Have one FxA account without subscription;
* Have the VPN installed on your machine;

#### Steps to reproduce:
1. Login to VPN with the account from prerequisites;
1. Go to Settings-> App Permissions;
1. Disable the App Permission feature;
1. Turn ON the VPN;
1. Go back to App Permissions page;
1. Observe the switch button.

#### Expected result:
* There are no display or layout issues.

#### Actual result:
* A small flicker can be seen on the button.

#### Notes:
* Not reproducing on Windows.
![Captura de pantalla 2021-07-23 16](https://user-images.githubusercontent.com/15685960/126798747-c052ec8d-e289-432a-ab97-83da7f01f6a7.png)UNITO-UNDERSCORE!45!UNITO-UNDERSCORE!15!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-788)
┆Reporter: Data Sync

**Comment by ValentinaPC** [comment] 2021-08-20 07:34
Verified this while using VPN 2.5 (2.202108191036) while using Linux Ubuntu 20.04.
The flicker is still present.

https://user-images.githubusercontent.com/15685960/130197441-93a8da02-3f73-47ed-9ed3-a4983e979c4b.mp4

**Comment by data-sync-user** [comment] 2021-09-22 15:55
➤ Luminita Buruian commented:

Jeremy Swinarton Has this been fixed, as the last comment stated that the issue was still reproducing?

Thank you.

**Comment by data-sync-user** [comment] 2021-09-28 14:15
➤ Luminita Buruian commented:

Checked this today on Mozilla VPN 2.6.0 (2.202109281203) on Windows 10.

Although less visible,  the flicker on the App permission button reproduces on windows as well. This can no longer be checked with VPN on though.

CC: Valentina Virlics

**Comment by data-sync-user** [comment] 2021-10-13 06:36
➤ Valentina Virlics commented:

Hello, Jeremy Swinarton ! My initial issue was also referring to the button flicker. But, if there was something else that needed fixing, better! Thanks for taking care of it. ❤️

**Comment by data-sync-user** [comment] 2022-02-11 11:11
➤ Bianca Hidecuti commented:

I am reproducing this issue while being on the “Language” screen, on Mozilla VPN 2.7.0 (2.202202110108) - QT6 build, while using MacOS 11.6, and on Mozilla VPN 2.7.0 (16445420) - QT6 build, while using Android. Please see the attached video.

Thank you. 

!Screen Recording 2022-02-11 at 12.24.08.mov|width=722,height=1098!

**Comment by data-sync-user** [comment] 2023-02-22 16:05
➤ Lesley Norton commented:

Closing since as of 2.15 the new UI for this screen does not include the switch

**Closed by data-sync-user** 2023-02-22 16:05 UTC
Labels: bug, linux, qa_minor
