### ISSUE TITLE
Download and upload speeds are reversed on Mac OS

### ISSUE THREAD

**Issue by chrismore** [mozilla-mobile/mozilla-vpn-client#529] opened 2021-02-01 14:23 UTC
It appears that the download and upload speeds when viewed by clicking the "i" icon.

When downloading a file as a test, the upload speed was much higher than download, thus the UI must be reversed in the VPN client. 

@ValentinaPC can you help verify if you are seeing this too?

**Comment by ValentinaPC** [comment] 2021-02-01 15:35
@chrismore I was not able to reproduce the issue on my side.
I've checked Windows and Android. The speeds seemed to be corresponding to the performed action.

**Comment by bakulf** [comment] 2021-02-01 15:41
Right. This happens on macos only.

**Comment by chrismore** [comment] 2021-02-01 16:09
Updated this to be specific to Mac

**Comment by ValentinaPC** [comment] 2021-02-22 09:19
Verified the fix on macOS 10.15.7, the download speed test is reflected in the graph but the upload speed does not change during an upload speed test.
Reopening.

**Comment by bakulf** [comment] 2021-02-22 15:43
Was the local-area network access or the captive portal feature enabled? If yes, I suspect the problem is related to the IP address filtering

**Comment by ValentinaPC** [comment] 2021-02-23 07:18
> Was the local-area network access or the captive portal feature enabled? If yes, I suspect the problem is related to the IP address filtering

Captive portal is not available nor is local area network access on macOS, build 2.0.4. Although after enabling IPv6 it appears that the download and upload speed are displayed correctly on the Connection Information screen.

**Comment by ValentinaPC** [comment] 2021-03-04 15:26
Verified the issue with Mozilla VPN 2.0.4 latest build on macOS 10.15.7. 
Download and upload speeds are correctly reflected in Connection information screen. 
Closing issue as verified.

**Closed by ValentinaPC** 2021-03-04 15:26 UTC
Labels: macos, p1
