### ISSUE TITLE
VPN does not automatically restart after update (windows)

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#660] opened 2021-03-09 14:08 UTC
#### Affected Platforms:
* Windows 10 x64;

**Prerequisites:**

* Have the VPN app installed;
* Have a FxA account with a subscription made for VPN;

#### Steps to reproduce:
1. Launch VPN app;
1. Sign in and turn the VPN ON;
1. Reach [https://http://localhost:8766/](https://http//localhost:8766/) and enter command: triggerUpdate 1.0;
1. Click on the "Update now" button;
1. Observe the behavior;

**Expected result:**

* App is restarted after update.

**Actual result:**

* App does not restart automatically after update.
![width=200,height=183](https://user-images.githubusercontent.com/15685960/110482605-84e4e880-80f1-11eb-9231-6edfc4bf44cf.gif)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-116)
┆author: Data Sync

**Comment by data-sync-user** [comment] 2021-12-16 15:24
➤ Andrea Marchesini commented:

This issue is old and I wonder if it's already fixed.
Can the QA team check it again? Thanks!

**Comment by data-sync-user** [comment] 2021-12-20 12:22
➤ Valentina Virlics commented:

This can be rechecked as soon as the update is working.

**Comment by data-sync-user** [comment] 2022-01-28 06:55
➤ Valentina Virlics commented:

Verified this on the latest 2.7 VPN build, with Balrog updated and it is still reproducing.

**Comment by data-sync-user** [comment] 2022-05-05 16:13
➤ Andrea Marchesini commented:

Can you reproduce it with 2.9/2.8.3 too?

**Comment by data-sync-user** [comment] 2022-05-06 07:21
➤ Valentina Virlics commented:

Andrea Marchesini Verified this while using the last build from main branch, but after triggering the update via inspector (recommended or required) and clicking on the update button, the installer starts, but after that nothing happens.

I assume that this is due to the fact the Balrog has 2.8 version on?

Let me know if there is another way I could check this using the latest VPN version.

Thanks!

**Comment by data-sync-user** [comment] 2022-05-25 16:59
➤ Andrea Marchesini commented:

We have changed several things in the installer. Can you please test it again?
Thank you!

**Comment by data-sync-user** [comment] 2022-05-26 08:11
➤ Valentina Virlics commented:

Sure!

I’ve verified this while making an update from Mozilla VPN 2.8.3 (2.202205061614) build from Download page using the Inspector.

The update was made with success, but the app did not restart.

From 2.8.4 could not try, probably because of Balrog?

Attaching logs for the first situation.

[^mozillavpn-2022-5-26.txt]

**Comment by data-sync-user** [comment] 2022-05-26 09:09
➤ Valentina Virlics commented:

Also, only Windows, installing a version of the client - 2.8.4 - while having the client already installed, generates the same behavior: the app does not starts.

Andrea Marchesini Let me know when the PR that changes the installer lands, to recheck this.

**Comment by data-sync-user** [comment] 2022-05-30 11:46
➤ Valentina Virlics commented:

Moving this into blocked until Balrog will be update for 2.9 release.

**Comment by data-sync-user** [comment] 2022-06-17 09:55
➤ Bianca Hidecuti commented:

Moving this into “Dev Complete” state as we are waiting for Balrog to be updated in order to start testing it.

**Comment by data-sync-user** [comment] 2022-07-19 08:43
➤ Andrea Marchesini commented:

Sebastian Streich has balrog been updated?

**Comment by data-sync-user** [comment] 2022-07-19 10:47
➤ Valentina Virlics commented:

Andrea Marchesini Yes, Balrog was updated.

Update works as expected using the “check for updates“ button, and the client restarts after it.

**Closed** 2022-07-19 10:47 UTC
Labels: bug, macos, windows, cross-platform, qa_major
