### ISSUE TITLE
VPN is in No Signal/Unstable state after waking the PC from standby

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1411] opened 2021-07-23 14:45 UTC
#### VPN version:
2.4.0 (2.202107230656)

#### Affected Platforms:
* Mac OS 10.15;

#### Prerequisites:
* Have one FxA account without subscription;
* Have the VPN installed on your machine;

#### Steps to reproduce:
1. Login to VPN with the account from prerequisites;
1. Turn ON the VPN;
1. Leave the PC to enter in stand by;
1. Start the PC and see VPN status;

#### Expected result:
* VPN is ON;

#### Actual result:
* VPN is in “No signal” state;

#### Notes:
* the “No signal” state turns into “unstable” and to “active” after a few seconds.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-789)
┆Reporter: Data Sync
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/VPN-789

**Comment by data-sync-user** [comment] 2021-11-02 11:21
➤ Valentina Virlics commented:

Verified this on the latest 2.6 builds on Windows, Linux Ubuntu 20.04/21.04, iOS and Android 10 and the issue is reproducing here also.

Might this be related with: https://mozilla-hub.atlassian.net/browse/VPN-1259 ( https://mozilla-hub.atlassian.net/browse/VPN-1259|smart-link ) ?

**Comment by data-sync-user** [comment] 2022-10-14 08:49
➤ Andrea Marchesini commented:

Valentina Virlics have you seen this recently?

**Comment by data-sync-user** [comment] 2022-10-14 14:06
➤ Bianca Hidecuti commented:

Andrea Marchesini , this is still happening on Mozilla VPN 2.10.0 (2.202210111517), while on MacOS 11.6. 

After waking the device from standby, the VPN enters in No signal state, and after a few seconds, the timer resets.

**Comment by data-sync-user** [comment] 2022-12-15 21:44
➤ Sarah Bird commented:

Closing in favor of more recent duplicate ticket.

**Closed by data-sync-user** 2022-12-15 21:44 UTC
Labels: bug, macos, qa_minor
