### ISSUE TITLE
Privacy Settings Ubuntu

### ISSUE THREAD

**Issue by srueegger** [mozilla-mobile/mozilla-vpn-client#7516] opened 2023-07-14 08:57 UTC
**Describe the bug**
The privacy setting in Mozilla VPN Client for Linux have a display problem.
See the screenshot.

![Bildschirmfoto vom 2023-07-14 10-53-19](https://github.com/mozilla-mobile/mozilla-vpn-client/assets/11472914/3b61124a-3f78-4c2f-a39c-9da9ab685e39)

**VPN version:**
mozillavpn 2.15.3

**Affected Platforms:**
  Ubuntu 23.04

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-5218)

**Comment by data-sync-user** [comment] 2023-07-14 09:12
➤ Bianca Hidecuti commented:

Hello,

Thank you for filling this ticket! This should be fixed with Mozilla VPN 2.16 version. See https://mozilla-hub.atlassian.net/browse/VPN-4494 ( https://mozilla-hub.atlassian.net/browse/VPN-4494|smart-link )

**Comment by data-sync-user** [comment] 2023-07-17 13:18
➤ Lesley Norton commented:

Thank you for filing! As Bianca Hidecuti mentioned, this will be fixed in the next release. Closing as duplicate of VPN-4494.

**Closed by data-sync-user** 2023-07-17 13:18 UTC
Labels: bug
