### ISSUE TITLE
Glean.js makes iOS to crash for too much stack recursion

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1599] opened 2021-08-20 15:46 UTC
We should fix this issue, asap! For now, let's disable glean for iOS.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-882)

**Comment by data-sync-user** [comment] 2021-08-25 16:42
➤ Nma-Sie-Anyene Davenport commented:

No action needed from PSP  team

**Comment by brizental** [comment] 2021-09-03 17:45
Hey folks, just an update here. Unfortunately I am not able to reproduce this bug in my own iPhone. 

If possible, it would be useful to check if the crash persists even when pings are sent without passing a signal from C++ to QML. Since the crash happens exactly at the time the signal is sent, maybe there is some issue with the communication between the two layers.

Also, do we have access to the JavaScript console logs at the time of the crash? That could potentially have important information about the crash. I would suggest enabling the [`logPings`](https://mozilla.github.io/glean/book/reference/debug/logPings.html) debug feature in Glean to have the most logs Glean will provide.

**Comment by data-sync-user** [comment] 2021-09-14 18:56
➤ Adrienne Davenport commented:

JR Johnson - Can you give us information regarding the frequency of this occurrence, please?

**Comment by data-sync-user** [comment] 2021-09-14 21:40
➤ JR Johnson commented:

Adrienne Davenport  I am not familiar with this issue currently. Can you give us identification criteria? If its as simple as inbound referring to IOS app crashes, then we have not seen any an impact ticket wise currently.

**Comment by data-sync-user** [comment] 2021-09-21 18:28
➤ Sarah Bird commented:

It’s actually Beatriz Rizental Machado who’s working on this. But I’m assigning it to me as I’m helping with fix verification and any other way I can, and it would be weird to have Beatriz on our sprint board.

**Comment by data-sync-user** [comment] 2021-09-21 18:29
➤ Sarah Bird commented:

Adrienne Davenport JR Johnson this is not happening in production as we disabled glean on iOS to prevent it happening in production.

**Closed** 2021-10-18 20:47 UTC
Labels: bug, iOS, p2
