### ISSUE TITLE
VPN disconnects after toggling switch to on

### ISSUE THREAD

**Issue by jr-johnson-support** [mozilla-mobile/mozilla-vpn-client#966] opened 2021-05-04 21:12 UTC
Users are reporting that when trying to connect to the VPN it is not connecting and stays off as soon as they tap the switch.

**Technical Information**

* Device version macOS 11.2.3, Also seen on Windows
* FX product Mozilla VPN
* FX version VPN 2.2.0 
* Any other additional info
**Steps to Reproduce**

1. download/install VPN
1. sign in to VPN with fxa
1. tap switch to connect with VPN
1. VPN switch will be green and say is On

**Actual Results**

* VPN does not remain On when trying to connect

[Disconnection Logs 2.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6423977/Disconnection.Logs.2.txt)
[Disconnection logs 1.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6423979/Disconnection.logs.1.txt)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-176)

**Comment by birdsarah** [comment] 2021-05-24 19:01
@strseb adding you to this issue as we were working on it together.

**Comment by jr-johnson-support** [comment] 2021-05-27 14:48
@birdsarah @strseb  Interestingly we got a user on the forum who noted this issue above and they were able to find a solution. This is specifically Windows not mac, though I thought you should check out the details to see if their solution is potentially the solution for all users running into this. 

https://support.mozilla.org/en-US/questions/1336981

The user noticed services for Mozilla VPN were disabled. He changed the startup for the services to automatic which resolved the disconnect issue after toggling the app on.

**Comment by jr-johnson-support** [comment] 2021-06-16 16:00
54 tickets submitted since this issue was surfaced

**Comment by jr-johnson-support** [comment] 2021-07-12 14:40
68 users impacted with users on V2.3 showing up in there. 

Logs from a recent users experiencing the issue. 
[mozillavpn-2021-7-8.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6802232/mozillavpn-2021-7-8.txt)

**Comment by strseb** [comment] 2021-07-12 16:04
@birdsarah 
Looking at the logs: the activation again ends that getdnsservers but my thought is there are spaces in the wifi adapter name.
Because in that case  we should call `networksetup -getdnsservers "802.11ac WLAN Adapter" ` but the script calls 

`get_response="$(cmd networksetup -getdnsservers "$service" |tr '\n' '-')"`
would this make sense:?
`get_response="$(cmd networksetup -getdnsservers '"$service"' |tr '\n' '-')"`

```
[#] networksetup -getdnsservers Ethernet
[#] networksetup -getsearchdomains Ethernet
[#] networksetup -getdnsservers 802.11ac WLAN Adapter
[#] rm -f /var/run/wireguard/utun2.sock
[#] rm -f /var/run/wireguard/moz0.name
```

**Comment by madalincm** [comment] 2021-07-22 09:30
Verified this on Mozilla VPN v. 2.3.2 (2.202106171827) while using MacOS Big Sur 11.4 and I dont' reproduce it. The VPN stays connected after switching the toggle button to turn the VPN on.

**Comment by JKingZapata** [comment] 2021-09-14 21:14
Issue still happening on 2.4

[macOS logs.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/7165171/macOS.logs.txt)

**Comment by JKingZapata** [comment] 2021-09-14 21:16
Also adding Mac system information and ifconfig results
![2rvYThT94y1uaTTjB66vwckAs](https://user-images.githubusercontent.com/72564534/133334974-3f2b7a65-30bd-41ff-8549-017fd7e32308.png)

<img width="481" alt="8WAoPk7yqmi9DGWq3A7ZX7fiq" src="https://user-images.githubusercontent.com/72564534/133335063-64d29338-4a3f-409b-af67-9a8ee546f645.png">

<img width="480" alt="BzkInmeQcJ2dvCPjVLOBJg73I" src="https://user-images.githubusercontent.com/72564534/133335082-e807193d-4947-492f-8a54-faf05c5c6ae9.png">

**Comment by JKingZapata** [comment] 2021-10-06 16:52
Have not received any new tickets since 2.5 was released.

**Comment by data-sync-user** [comment] 2021-12-17 13:49
➤ Andrea Marchesini commented:

No new issues from v2.5. Closing.

**Closed by data-sync-user** 2021-12-17 13:49 UTC
Labels: macos, windows, p2, prod_bug
