### ISSUE TITLE
Fritzbox blocked when VPN is turned on

### ISSUE THREAD

**Issue by jr-johnson-support** [mozilla-mobile/mozilla-vpn-client#1136] opened 2021-06-01 14:26 UTC
**Description**
Users in Germany are unable to access Fritz.box to manage their router while Mozilla VPN is connected 

**Technical Information**

* Device version 
* FX product: Mozilla VPN: 
* FX version: 2.2.0 (Windows and MacOS)
* Any other additional info

**Steps to Reproduce**

1. Install Mozilla VPN and turn it on
2. user enters their IP address or fritz.box in the browser's search bar
3. 
4.  

**Actual Results**

1. User installs Mozilla VPN and turns it on
2. user enters their IP address or fritz.box in the browser's search bar
3. page does not load or is blocked
4. User is unable to manage their router settings unless the turn the VPN off 

Mitigation Steps: 

1. Have the user enable LNA in the VPN settings then retest access to the URL. (This has resolved issue for several windows users. 

We have recently had a MacOS user with the same issue. Logs attached. 
[ticket22550logs.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6576942/ticket22550logs.txt)

**Comment by oskirby** [comment] 2021-06-01 21:15
I don't know that there is a good solution to this issue that wouldn't result in a leak of the VPN activity via DNS. From what I understand of the Fritz!Box, it is hosting a local DNS resolver on the router that intercepts queries for the name "fritz.box" and replaces it with the internal IP address of the router. By design, once activated, the VPN will forward all DNS queries to Mullvad for resolving who won't have the knowledge of what to resolve "fritz.box" to. I'm not sure if it's even a valid TLD.

**Comment by rbillings** [comment] 2021-06-02 16:12
The solution will be to create a known issue article to share with customers.

**Closed by rbillings** 2021-06-02 16:12 UTC
Labels: macos, prod-bug, windows

**Comment by data-sync-user** [comment] 2021-09-01 21:43
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been opened in error by the data sync.
