### ISSUE TITLE
VPN loses internet connection when connected to cellular network

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#4823] opened 2022-11-03 20:29 UTC
**Description**
iOS 16 users on 2.10 cannot connect to internet when VPN is On and using cellular network, seeing error (no signal). VPN sometimes becomes unresponsive and have to reboot device to regain internet access, but with VPN off. Issue does not occur when connected to WiFI. Basic TS (uninstalling/reinstalling does not remedy the issue) Support cannot reproduce the issue.

Does it impact functionality or aesthetics? Yes
Does this endanger users? What would be compromised and how likely is the threat? No
How annoying is this for affected users? (Think about how much 'in the way' this is, relative to what the user is trying to do) Yes
Does it degrade the user experience significantly? Yes
Is it legally sensitive? No

**Centrality** 
Is it on a core user journey or on a secondary one?  Core user journey (connection)

**Technical Information**

Platform iOS 16
FX product Mozilla VPN
Version 2.10
Region/Languages
Network type Mobile
Cellular carriers reported: Third, UK

**Steps to Reproduce**
1. Purchase subscription
2. Install VPN client
3. Sign in to Fxa
4. Connect to any location 
5. Use Cellular network

**Actual Results**
When device is connected on cellular network VPN displays no signal message and internet connectivity is lost

**Expected Results**
No error message should appear on VPN. Device should remain connected to internet regardless of using WiFI or Cellular.

[MozillaVPN-logs 3.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/9932760/MozillaVPN-logs.3.txt)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-3172)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/VPN-3172

**Comment by data-sync-user** [comment] 2022-11-04 09:10
➤ Bianca Hidecuti commented:

QA is not able to verify this scenario as we are not able to connect to the internet while using cellular data on our testing devices.

**Comment by data-sync-user** [comment] 2022-11-07 20:11
➤ Matt Cleinman commented:

I was able to replicate this over the weekend on iOS 16 and v2.10. 

It’s related to iOS 16 VPN issues. While our VPN is working on WiFi, it’s still having trouble on cellular. Making it worse, it’s continually trying to connect on a loop (which you can see in the iOS Settings app, by watching the VPN toggle). For most of that (failing) connection cycle, for some reason iOS is swallowing Apple-related traffic. Thus: Apple Maps, Siri, iMessage (and presumably others) show as having no connection while on cellular.

The only fix for this is to delete the VPN from iOS Settings app. This stops the re-connecting cycle on cellular. Then, while next on wifi, toggle on the VPN (in the Mozilla VPN app) and let the Mozilla VPN app re-install the iOS plumbing for the VPN.

**Comment by data-sync-user** [comment] 2022-11-07 20:11
➤ Matt Cleinman commented:

Also, potentially this issue should be closed as a duplicate of this one: https://mozilla-hub.atlassian.net/browse/VPN-3185 ( https://mozilla-hub.atlassian.net/browse/VPN-3185|smart-link )

**Comment by data-sync-user** [comment] 2022-11-08 00:40
➤ Matt Cleinman commented:

Partway through debugging this, going to pick it back up in the morning. These notes are as much for me as for anyone else.

    - [ ] We get a notification from iOS when it’s VPN status changes. I can see this over and over:
        - [ ] [07.11.2022 16:14:33.228] Debug: (ios - IOSSGlue) Swift log - tag: APP msg:  STATE CHANGED: connecting
        - [ ] [07.11.2022 16:14:38.433] Debug: (ios - IOSSGlue) Swift log - tag: APP msg:  STATE CHANGED: disconnecting
        - [ ] [07.11.2022 16:14:39.787] Debug: (ios - IOSSGlue) Swift log - tag: APP msg:  STATE CHANGED: disconnected
    - [ ] Of course, why is it disconnecting? We’re not getting anything helpful in the logs.
    - [ ] Ideas
        - [ ] There is some plug in that needs to be updated
        - [ ] There is some setting that is wrong
    - [ ] What would be helpful
        - [ ] Some more insight into what is happening w/ iOS
            - [ ] Found something! There is a `(notification.object as! NETunnelProviderSession).fetchLastDisconnectError` This should give us exactly what we need!
            - [ ] And what we get - 
                - [ ] Error Domain=NEVPNConnectionErrorDomain Code=12 "The VPN session failed because an internal error occurred." UserInfo={NSLocalizedDescription=The VPN session failed because an internal error occurred.}
                - [ ] Hahahahaha that is so unhelpful. Let’s search the internet for “NEVPNConnectionErrorDomain” and see if we find anything with that…
                    - [ ] Hahahhaha A+ documentation Apple: <https://developer.apple.com/documentation/networkextension/nevpnconnectionerrordomain?changes=lat_3_1_5>
                        - [ ] Hmmm, actually - this error type is new in iOS 16. Maybe that’s relevant?
                - [ ] Searching the “The VPN session failed because an internal error occurred.” error
                - [ ] Well, there is an XKCD for everything: <https://stackoverflow.com/questions/56174241/how-to-debug-network-extension> / <https://xkcd.com/979/>
                - [ ] OK, I have a few potentially helpful links for debugging this. Going to be diving into them tomorrow.

**Comment by data-sync-user** [comment] 2022-11-10 22:55
➤ Matt Cleinman commented:

I finally got some logs from the iOS Network Extension.

The key parts -

Successful connection on Wifi:

default	14:42:44.949409-0800	nesessionmanager	NESMVPNSession[Primary Tunnel:Mozilla VPN:DB6C5D63-DCF9-4D10-9CDD-64FC48FBEEDC:(null)]: didSetStatus - 4
default	14:42:44.949561-0800	nesessionmanager	NESMVPNSession[Primary Tunnel:Mozilla VPN:DB6C5D63-DCF9-4D10-9CDD-64FC48FBEEDC:(null)] in state NESMVPNSessionStateStarting: plugin NEVPNTunnelPlugin(org.mozilla.ios.FirefoxVPN[inactive]) status changed to connected
default	14:42:44.949706-0800	nesessionmanager	NESMVPNSession[Primary Tunnel:Mozilla VPN:DB6C5D63-DCF9-4D10-9CDD-64FC48FBEEDC:(null)]: Leaving state NESMVPNSessionStateStarting
default	14:42:44.949740-0800	nesessionmanager	NESMVPNSession[Primary Tunnel:Mozilla VPN:DB6C5D63-DCF9-4D10-9CDD-64FC48FBEEDC:(null)]: Entering state NESMVPNSessionStateRunning
default	14:42:44.949865-0800	nesessionmanager	NESMVPNSession[Primary Tunnel:Mozilla VPN:DB6C5D63-DCF9-4D10-9CDD-64FC48FBEEDC:(null)]: status changed to connectedFailed connection on cellular:

default	14:45:17.540846-0800	nesessionmanager	NESMVPNSession[Primary Tunnel:Mozilla VPN:DB6C5D63-DCF9-4D10-9CDD-64FC48FBEEDC:(null)]: didSetStatus - 0
default	14:45:17.540924-0800	nesessionmanager	NESMVPNSession[Primary Tunnel:Mozilla VPN:DB6C5D63-DCF9-4D10-9CDD-64FC48FBEEDC:(null)] in state NESMVPNSessionStateStarting: plugin NEVPNTunnelPlugin(org.mozilla.ios.FirefoxVPN[inactive]) disconnected with reason Plugin failed
default	14:45:17.547934-0800	nesessionmanager	NESMVPNSession[Primary Tunnel:Mozilla VPN:DB6C5D63-DCF9-4D10-9CDD-64FC48FBEEDC:(null)]: Leaving state NESMVPNSessionStateStarting
default	14:45:17.548005-0800	nesessionmanager	NESMVPNSession[Primary Tunnel:Mozilla VPN:DB6C5D63-DCF9-4D10-9CDD-64FC48FBEEDC:(null)]: Entering state NESMVPNSessionStateStopping, timeout 20 seconds
default	14:45:17.548100-0800	nesessionmanager	NESMVPNSession[Primary Tunnel:Mozilla VPN:DB6C5D63-DCF9-4D10-9CDD-64FC48FBEEDC:(null)]: config request: pushing handler [(null)] (null)
default	14:45:17.548146-0800	nesessionmanager	<NESMServer: 0x610904860>: Request to uninstall session: NESMVPNSession[Primary Tunnel:Mozilla VPN:DB6C5D63-DCF9-4D10-9CDD-64FC48FBEEDC:(null)]
default	14:45:17.548187-0800	nesessionmanager	NESMVPNSession[Primary Tunnel:Mozilla VPN:DB6C5D63-DCF9-4D10-9CDD-64FC48FBEEDC:(null)]: status changed to disconnecting

**Comment by data-sync-user** [comment] 2022-11-11 00:32
➤ Matt Cleinman commented:

The brain dump of the day is here, but the exciting bit: I have isolated which line is causing the crash. In WireGuardAdapter.swift, self.packetTunnelProvider?.setTunnelNetworkSettings(networkSettings) errors. Hopefully I’ll shortly have another update with why.

                    - [ ] I’ve found 3 search results (but none were helpful) for NEVPNTunnelPlugin "disconnected with reason Plugin failed"
                    - [ ] OK, logs before were locked on network extension. It seems to be an interaction w/ our app possibly, so let’s look at all logs around there.
                        - [ ] This was a bit above that line, and feels like we’re getting close. Perhaps there is a callback in our app we’re not handling well?
                            - [ ] default	14:25:50.391587-0800	ReportCrash	Formulating fatal 309 report for corpse[27132] MozillaVPNNetworkExtension
                        - [ ] Oooh, getting closer
                            - [ ] default	14:25:48.707515-0800	MozillaVPNNetworkExtension	Swift/arm64-apple-ios.swiftinterface:23519: Fatal error
                        - [ ] Potentially pertinent
                            - [ ] error	14:25:47.934644-0800	MozillaVPNNetworkExtension	peer(Az+P…4si4) - Failed to send data packet: write udp4 0.0.0.0:55882->37.19.210.27:22814: sendto: network is unreachable
                            - [ ] FWIW, I can ping this from my phone both on cellular and wifi                - [ ] So I’m trying to debug the extension, as the problem is clearly there. And it’s only 22 files or so, according to the build settings. 
                    - [ ] It’s not respecting breakpoints or breakpoints - either in the code, or for exceptions. This seemed the case from earlier testing, but still big annoyed energy.
                    - [ ] It seems that the logging isn’t set up in the extension in a way that actually has it output into our logs. I can do it w/ os_log. Let me try to fix the logging real quick, and then if that works maybe it will give us another crumb.
                    - [ ] OK, it’s actually logging in main console, just not in Xcode (even though we’re running the extension) - at least when we’re activating VPN via system and not our app. So let’s try that
                    - [ ] IF THESE LOGS DON’T PULL ANTYHING, CAN I PULL THE CRASH OFF THE DEVICE?
                        - [ ] Hmmm, I don’t see crash logs for this on my device
                    - [ ] So let’s pull same logging as before (wifi vs. cellular), but locking on the MozillaVPNNetworkExtension
                        - [ ] Here is a diff
                            - [ ] Cell: 
                                - [ ] nw_path_evaluator_start [0A434EA9-9B34-4A2D-BB06-4B2EF4054CEA <NULL> generic, multipath service: 1, attribution: developer]
                                - [ ] path: satisfied (Path is satisfied), interface: pdp_ip0, scoped, ipv6, dns, expensive
                            - [ ] Wifi
                                - [ ] nw_path_evaluator_start [D3A5CB72-7068-4429-9168-EDC0E605835C <NULL> generic, multipath service: 1, attribution: developer]
                                - [ ] path: satisfied (Path is satisfied), interface: en0[802.11], scoped, ipv4, dns
                            - [ ] This basically confirms it’s ipv6. But is the word “expensive” there also a problem? Or just how it signals a metered connection for it’s internal stuff? 
                        - [ ] Can confirm identical DNS settings bing set
                        - [ ] OK, so the crash is directly after we get those DNS settings - the start of that DNS setting line is
                            - [ ] [Extension org.mozilla.ios.FirefoxVPN.network-extension]: provider set tunnel configuration to 
                            - [ ] Cell has 
                                - [ ] container_create_or_lookup_app_group_path_by_app_group_identifier: success
                            - [ ] And this line is successful at other places on cellular. Hmmmm
                    - [ ] OK, WE HAVE ISOLATED TO WHICH LINE IS CAUSING THIS. It’s in WireGuardAdapter.swift
                        - [ ] self.packetTunnelProvider?.setTunnelNetworkSettings(networkSettings) { error in

**Comment by data-sync-user** [comment] 2022-11-11 01:18
➤ Matt Cleinman commented:

We’re getting a ping error. Which on some level makes sense - we’re trying to hit an IPv4 address on a network that seems to only support IPv6. I’m not an expert on the IPv4 to IPv6 transition, so I’d probably want to check with somebody who understands it better. But this seems like maybe it should be what we get.

I’m going to try setting the VPN up on IPv6 again - let’s see what error that gets. Because if I can finally get that working, then we just need some code to decide whether we should use IPv4 or IPv6 for the connection.

Interesting, it’s the same error. So I’m going to look at what is in the networkSettings that we’re passing in here - maybe something is getting added that just doesn’t work for IPv6 networks.

There are 3 paths to calling setNetworkTunnelSettings, and all 3 use PacketTunnelSettingsGenerator's generateNetworkSettings to create their networkSettings argument.

OK, this has GOT to be related to this line in generateNetworkSettings

let networkSettings = NEPacketTunnelNetworkSettings(tunnelRemoteAddress: "127.0.0.1")

Actually, this might not be it. The comment WireGuard leaves there: 

/* iOS requires a tunnel endpoint, whereas in WireGuard it's valid for
         * a tunnel to have no endpoint, or for there to be many endpoints, in
         * which case, displaying a single one in settings doesn't really
         * make sense. So, we fill it in with this placeholder, which is not
         * a valid IP address that will actually route over the Internet.
         */A search ( https://www.google.com/search?hl=en&q=tunnelRemoteAddress%20ipv6 ) led me to this page:

https://developer.apple.com/forums/thread/660293 ( https://developer.apple.com/forums/thread/660293|smart-link )

Which in turn led me to this page:

https://developer.apple.com/forums/thread/107283?answerId=359856022#359856022 ( https://developer.apple.com/forums/thread/107283?answerId=359856022#359856022|smart-link )

Which implied that the includeAllNetworks flag may have something to do with this. And you know what? When on my cell network, while using the IPv6 destination IPs, I usually get the ping error in the logs. But when I update `ioscontroller.swift` to proto!.includeAllNetworks = false (we usually set it to true), the ping errors go away. It doesn’t fix everything - the connection still fails. But this does seem to be part of the problem.

Will be picking this up on the next work day.

Next up for me:

  * Play more with this includeAllNetworks. If it’s false, what is the error message? Can I modify code to get a connection?
  * Look more at generateNetworkSettings. What happens if I hack it to be a very simple file? Can we get it to stop crashing?
  * Do more searching around this problem, now that we know what iOS SDK line it’s isolated to.

**Comment by data-sync-user** [comment] 2022-11-15 01:06
➤ Matt Cleinman commented:

Today’s notes below. NordVPN works on cellular, but after I tested it, I realized it’s closed source. I can’t figure out how they’re setting up the connection (and what is different than what we’re doing), or even confirm that they’re using WireGuard. I’m going to repeat this tomorrow, but with a client that is confirmed to be open source and using WireGuard.

            - [ ] Play more with this includeAllNetworks. If it’s false, what is the error message? Can I modify code to get a connection?
                - [ ] It’s not this, for sure. includeAllNetworks just swallows all traffic when true. So when this is false, I can connect to other services, as expected - but it doesn’t change how I (don’t) connect to our VPN network.
            - [ ] Look more at generateNetworkSettings. What happens if I hack it to be a very simple file? Can we get it to stop crashing?
                - [ ] First thing, something I saw before: That tunnel remote address. Let me try:
                    - [ ] Changing it to some random IPv4 address - does it still work on wifi?
                        - [ ] 128.027.638.114 - it struggles to connect
                        - [ ] But on 127.0.0.1 (default), it works
                        - [ ] This seems important. So, what is localhost for IPv6?
                        - [ ] It’s “[::1]”. Trying this. And will remove brackets if it doesn’t work.
                        - [ ] Fun fact: When the VPN is active, Xcode has trouble installing the app to a device. How many times will I forget that while debugging? If past is prologue, the answer is a LOT.
                        - [ ] Changed to [::1]: Doesn’t work on wifi (as I’d expect) nor cellular.
                        - [ ] Changed to ::1: Connects on wifi, but not cellular. Key here is “connects”, as while I’m connected to the VPN it seems to have an inactive connection.
                            - [ ] My connection code still has IPv4 stuff. Let’s change it to IPv6 - while keeping it to ::1 - and see what happens.
                                - [ ] With ::1 (in let networkSettings = NEPacketTunnelNetworkSettings(tunnelRemoteAddress: “::1”)) and 2 IPv6 addresses in iosController.swift, of the form let fullV6 = "["+serverIpv6AddrIn+"]" + ":\(serverPort )"
                                    - [ ] This fails
                                - [ ] Trying: ::1 w/ 2 iosController snippets using serverIpv6AddrIn+"" + ":\(serverPort )" (no brackets)
                                    - [ ] This connects on both wifi and cellular to VPN, but there is no connection within the VPN
                                    - [ ] NOTE: I CAN CONTROL VPN IN THIS CASE FROM IOS SETTINGS, BUT NOT APP. WHY? Am I actually using the new settings?
                                - [ ] Trying: ::1 w/ 2 iosController snippets using serverIpv6AddrIn (no brackets or server port)
                                    - [ ] This connects on cellular to VPN, but there is no connection within the VPN
                                    - [ ] On Wifi, it cuts the wifi connections and goes to cell. IS THIS IMPORTANT?
                                - [ ] Let’s look at the logs, and the errors.
                                - [ ] But first, looking at `generateNetworkSettings`. Since we’ve adjusted to an IPv6 address, the only potential problems here that I can guess would be some DNS code. 
                                    - [ ] Let me ping an IP address when we’re connected on cellular, and see if that works.
                                    - [ ] Nope. It definitely isn’t resolving DNS queries, but IP-only pings also don’t work.
                                - [ ] OK, looking at system logs. To be clear: On Cellular. TunnelRemoteAddress set to “::1”. iOS controller using serverIPv6AddrIn w/o brackets or a port.
                            - [ ] OK, checking out NordVPN, who Santiago has said uses Wireguard. It works for me on WiFi, and for cellular.
                                - [ ] Looking at their code to see if they have a similar setup.
                                - [ ] Unfortunately, it doesn’t seem like they’re open source. 
                                - [ ] TOMORROW, we’re going to repeat this same step but w/ someone who is open source, to see if it’s us or not.

**Comment by data-sync-user** [comment] 2022-11-16 01:59
➤ Matt Cleinman commented:

- [ ] TRY OTHER APPS
                - [ ] NOTE: NordVPN shows a connection IP that is IPv4 when on cellular. 
                    - [ ] Hmmm… What happens when I put it back to IPv4 stuff… maybe there is just some simple setting I’m neglecting? Look at my settings on Wifi, and my settings on cell, and compare that to wifi and cellular w/ NordVPN.
                    - [ ] Try again w/ IPv4 localhost, compare screenshots
                        - [ ] Nord VPN doesn’t provide an IPv6 address. Hmmm. https://nordvpn.com/blog/ipv6-enable-or-disable/
                            - [ ] Looks like they tunnel IPv6, but only via IPv4. Should we try that?
                            - [ ] NordVPN also doesn't seem to be open source. :angry-face:
                    - [ ] Could it be something about including a port in the IP?
                    - [ ] Could it somehow be related to our DNS settings?
                    - [ ] WireGuard for iOS has not been updated in 14 months. Is this an issue?
                    - [ ] Tried Mullvad. It works fine on cell there. So now let’s dig in and see the difference between our two codebases.
                        - [ ] 1. Do they use same WireGuard as us? They use the SPM WireGuardKit. What version is this running? Seems like it is a derivative of https://lists.zx2c4.com/pipermail/wireguard/2020-December/006161.html
                            - [ ] They run their own fork… that’s probably helpful. There are only a handful of commits since iOS 16 entered developer beta.
                            - [ ] And we have it! https://github.com/WireGuard/wireguard-apple/commit/fe90def15c601722a5fb6688485ab277a15a37df
                                - [ ] Making this fix in our version of wireguard fixes it for us.
                                - [ ] And…. Six hours ago somebody put up a PR for Wireguard. 
                                - [ ] Next up: Put up PR. Make sure no unintended consequences.

**Comment by data-sync-user** [comment] 2022-11-16 19:38
➤ Matt Cleinman commented:

PR is up for a fork of the wireguard-apple repo: https://github.com/mozilla/wireguard-apple/pull/1 ( https://github.com/mozilla/wireguard-apple/pull/1|smart-link )
After that gets merged, I’ll put up a PR for the VPN repo.

**Comment by data-sync-user** [comment] 2022-11-16 22:39
➤ Matt Cleinman commented:

PR is now up for VPN repo: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/4954 ( https://github.com/mozilla-mobile/mozilla-vpn-client/pull/4954|smart-link )

**Comment by data-sync-user** [comment] 2022-12-01 22:58
➤ Santiago Andrigo commented:

Moving to “Done” as this is live now.

**Closed by data-sync-user** 2022-12-01 22:58 UTC
