### ISSUE TITLE
Bad CMake config on Debian bookworm

### ISSUE THREAD

**Issue by matthew-mcallister** [mozilla-mobile/mozilla-vpn-client#6789] opened 2023-05-01 04:01 UTC
**Describe the bug**
After successfully configuring with CMake, make fails due to an uninitialized CMake variable: QT_LUPDATE_EXECUTABLE-NOTFOUND. Manually updating CMakeCache.txt with `QT_LUPDATE_EXECUTABLE:FILEPATH=lupdate` (and similarly for lconvert and lrelease) fixes the issue. My guess is there's a missing CMake find_package call, or a call that isn't marked as required. Or the find module for lupdate/lconvert/lrelease is just very bad and doesn't find these binaries even when they are directly on the PATH.

**VPN version:**
master

**Affected Platforms:**
Debian bookworm

**Prerequisites:**
n/a

**Steps to reproduce:**
Attempt to compile on Debian bookworm with Qt5/Qt6 installed.

**Expected result:**
The software compiles

**Actual result:**
The software doesn't compile

**Additional notes:**
n/a

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-4703)

**Comment by marcel263** [comment] 2023-06-02 07:48
Unfortunately, the bug did not appear when searching for possible dupes. This is similar to #6899 except the required Fedora package was not actually installed, which once fixed resolved the false positive for lupdate during configuration, and compilation succeeded.

**Comment by data-sync-user** [comment] 2024-04-30 18:11
➤ Santiago Andrigo commented:

Duplicate of VPN-4777

**Closed by data-sync-user** 2024-04-30 18:11 UTC
Labels: bug
