### ISSUE TITLE
VPN won't connect on iOS 15 beta

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#1387] opened 2021-07-21 14:38 UTC
**Description**
Mozilla VPN does not connect after users updated to iOS 15 beta

**Technical Information**

* Device model iPhone 12
* Device version iOS 15
* FX product Mozilla VPN 2.3

**Steps to Reproduce**

1. Download/install Mozilla VPN from the app store
2. flip the switch to connect to VPN
3. VPN turns on and connects

**Actual Results**
1. Download/install Mozilla VPN from the app store
2. flip the switch to connect to VPN
3. VPN fails to connect and gives no error message

Response to Users:

* try doing a soft reset (uninstall/reinstall the VPN)
* Ask for debug logs and iPhone model they are using
* iOS 15 is in beta/preview version right now, we haven't officially tested it yet. 

Mozilla VPN logs
================

[09.07.2021 12:29:53.344] (main - LogHandler) Log file: /var/mobile/Containers/Data/Application/52ECA169-838A-4F89-AF94-799F45186D38/Library/Application Support/mozillavpn.txt
[09.07.2021 12:29:55.608] Warning: QIODevice::write (QTcpSocket): device not open
[09.07.2021 12:29:55.612] Warning: qrc:/ui/components/VPNPanel.qml:39:13: QML Image: Host unreachable (VPNPanel.qml:39)
[09.07.2021 12:29:55.827] (main - CloseEventHandler) Remove item
[09.07.2021 12:29:59.462] (main - CloseEventHandler) Remove item
[09.07.2021 12:30:01.678] (main - MozillaVPN) VPN tunnel activation
[09.07.2021 12:30:01.678] (main|controller - TaskControllerAction) TaskControllerAction created for activation
[09.07.2021 12:30:01.678] (main - MozillaVPN) Scheduling task:  TaskControllerAction
[09.07.2021 12:30:01.678] (main - MozillaVPN) Tasks:  1
[09.07.2021 12:30:01.678] (main|controller - TaskControllerAction) TaskControllerAction run
[09.07.2021 12:30:01.678] (controller - Controller) Activation 1
[09.07.2021 12:30:01.678] (controller - Controller) Setting state: 2
[09.07.2021 12:30:01.681] (main - MozillaVPN) Controller state changed
[09.07.2021 12:30:01.681] (main - StatusIcon) Show notification
[09.07.2021 12:30:01.686] (networking - ConnectionHealth) Connection state changed
[09.07.2021 12:30:01.686] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:30:01.686] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:30:01.687] (captiveportal - CaptivePortalDetection) Controller/Stability state changed
[09.07.2021 12:30:01.687] (networking - ConnectionDataHolder) state changed
[09.07.2021 12:30:01.687] (networking - ConnectionDataHolder) Resetting the data
[09.07.2021 12:30:01.687] (networking - ConnectionDataHolder) Updating IP address
[09.07.2021 12:30:01.687] (networking - ConnectionDataHolder) Skip Updating IP address, not connected
[09.07.2021 12:30:01.687] (main - SystemTrayHandler) Update context menu
[09.07.2021 12:30:01.700] (main - NotificationHandler) Show notification
[09.07.2021 12:30:01.700] (main|controller - TaskControllerAction) stateChanged received by to be ignored
[09.07.2021 12:30:01.700] (networking - ConnectionCheck) Stopping a connection check
[09.07.2021 12:30:01.700] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:30:01.700] (controller - Controller) Activation internal
[09.07.2021 12:30:01.701] (controller - Controller) Computing the allowed ip addresses
[09.07.2021 12:30:01.701] (controller - Controller) Catch all IPv4
[09.07.2021 12:30:01.701] (ios|controller - IOSController) IOSController activating us23-wireguard
[09.07.2021 12:30:01.702] (ios - IOSSGlue) Swift log - tag: APP msg:  Connecting
[09.07.2021 12:30:01.733] (ios - IOSSGlue) Swift log - tag: APP msg:  Saving the tunnel succeeded
[09.07.2021 12:30:01.733] (ios - IOSSGlue) Swift log - tag: APP msg:  Loading the tunnel succeeded
[09.07.2021 12:30:01.749] (ios - IOSSGlue) Swift log - tag: APP msg:  STATE CHANGED: connecting
[09.07.2021 12:30:02.653] (controller - TimerController) TimerController - Timeout: 1
[09.07.2021 12:30:04.868] (main - MozillaVPN) Task completed
[09.07.2021 12:30:04.869] (main - MozillaVPN) Tasks:  0
[09.07.2021 12:30:07.041] (ios - IOSSGlue) Swift log - tag: APP msg:  STATE CHANGED: disconnecting
[09.07.2021 12:30:07.390] (ios - IOSSGlue) Swift log - tag: APP msg:  STATE CHANGED: disconnected
[09.07.2021 12:30:07.391] (ios|controller - IOSController) State changed:  0
[09.07.2021 12:30:07.391] (controller - TimerController) TimerController - Operation completed: 1 0
[09.07.2021 12:30:07.391] (controller - Controller) Disconnected from state: 2
[09.07.2021 12:30:07.391] (networking - ConnectionCheck) Stopping a connection check
[09.07.2021 12:30:07.391] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:30:07.391] (controller - Controller) Setting state: 5
[09.07.2021 12:30:07.395] (main - MozillaVPN) Controller state changed
[09.07.2021 12:30:07.395] (main - StatusIcon) Show notification
[09.07.2021 12:30:07.397] (networking - ConnectionHealth) Connection state changed
[09.07.2021 12:30:07.397] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:30:07.397] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:30:07.398] (captiveportal - CaptivePortalDetection) Controller/Stability state changed
[09.07.2021 12:30:07.398] (networking - ConnectionDataHolder) state changed
[09.07.2021 12:30:07.398] (networking - ConnectionDataHolder) Resetting the data
[09.07.2021 12:30:07.398] (networking - ConnectionDataHolder) Updating IP address
[09.07.2021 12:30:07.398] (networking - ConnectionDataHolder) Skip Updating IP address, not connected
[09.07.2021 12:30:07.398] (main - SystemTrayHandler) Update context menu
[09.07.2021 12:30:07.408] (main - NotificationHandler) Show notification
[09.07.2021 12:30:08.960] (controller - Controller) Disconnected from state: 5
[09.07.2021 12:30:08.961] (networking - ConnectionCheck) Stopping a connection check
[09.07.2021 12:30:08.961] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:30:08.961] (controller - Controller) Setting state: 1
[09.07.2021 12:30:08.963] (main - MozillaVPN) Controller state changed
[09.07.2021 12:30:08.964] (main - StatusIcon) Show notification
[09.07.2021 12:30:08.967] (networking - ConnectionHealth) Connection state changed
[09.07.2021 12:30:08.967] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:30:08.967] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:30:08.967] (captiveportal - CaptivePortalDetection) Controller/Stability state changed
[09.07.2021 12:30:08.967] (networking - ConnectionDataHolder) state changed
[09.07.2021 12:30:08.967] (networking - ConnectionDataHolder) Resetting the data
[09.07.2021 12:30:08.968] (networking - ConnectionDataHolder) Updating IP address
[09.07.2021 12:30:08.968] (networking - ConnectionDataHolder) Skip Updating IP address, not connected
[09.07.2021 12:30:08.968] (main - SystemTrayHandler) Update context menu
[09.07.2021 12:30:08.978] (main - NotificationHandler) Show notification
[09.07.2021 12:30:10.319] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:30:10.319] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:30:10.319] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:30:12.386] (networking - ConnectionHealth) Resuming connection check from Suspension
[09.07.2021 12:30:12.388] (networking - ConnectionHealth) ConnectionHealth activated
[09.07.2021 12:30:14.932] (main - CloseEventHandler) Add stack view
[09.07.2021 12:30:14.935] Warning: qrc:/ui/components/VPNPanel.qml:39:13: QML Image: Host unreachable (VPNPanel.qml:39)
[09.07.2021 12:30:16.970] (main - MozillaVPN) View log requested
[09.07.2021 12:30:16.978] (main - CloseEventHandler) Add view
[09.07.2021 12:30:16.978] (main - MozillaVPN) Retrieve logs
[09.07.2021 12:30:16.980] (main - LogHandler) Log file: /var/mobile/Containers/Data/Application/52ECA169-838A-4F89-AF94-799F45186D38/Library/Application Support/mozillavpn.txt
[09.07.2021 12:30:16.981] (main - MozillaVPN) Logs from the backend service received
[09.07.2021 12:30:18.897] (main - MozillaVPN) Store in clipboard
[09.07.2021 12:30:20.032] (main - MozillaVPN) Store in clipboard
[09.07.2021 12:30:22.093] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:30:22.093] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:30:22.093] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:30:22.117] (main - CloseEventHandler) Remove item
[09.07.2021 12:30:23.002] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:30:23.002] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:30:23.002] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:30:41.656] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:30:41.657] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:30:41.657] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:30:41.964] (networking - ConnectionHealth) Resuming connection check from Suspension
[09.07.2021 12:30:41.964] (networking - ConnectionHealth) ConnectionHealth activated
[09.07.2021 12:30:49.216] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:30:49.216] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:30:49.216] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:30:49.831] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:30:49.831] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:30:49.831] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:31:13.506] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:31:13.506] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:31:13.506] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:31:13.886] (networking - ConnectionHealth) Resuming connection check from Suspension
[09.07.2021 12:31:13.886] (networking - ConnectionHealth) ConnectionHealth activated
[09.07.2021 12:31:16.178] (main - MozillaVPN) Opening link:  1
[09.07.2021 12:31:16.216] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:31:16.216] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:31:16.216] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:31:17.267] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:31:17.267] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:31:17.267] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:31:21.973] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:31:21.973] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:31:21.973] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:31:22.439] (networking - ConnectionHealth) Resuming connection check from Suspension
[09.07.2021 12:31:22.439] (networking - ConnectionHealth) ConnectionHealth activated
[09.07.2021 12:31:23.630] (main - MozillaVPN) Opening link:  4
[09.07.2021 12:31:23.665] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:31:23.665] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:31:23.665] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:31:24.453] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:31:24.453] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:31:24.453] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:31:40.828] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:31:40.829] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:31:40.829] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:31:41.297] (networking - ConnectionHealth) Resuming connection check from Suspension
[09.07.2021 12:31:41.297] (networking - ConnectionHealth) ConnectionHealth activated
[09.07.2021 12:31:48.243] (main - MozillaVPN) Opening link:  2
[09.07.2021 12:31:48.275] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:31:48.275] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:31:48.275] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:31:49.047] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:31:49.048] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:31:49.048] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:31:57.588] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:31:57.588] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:31:57.588] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:31:57.938] (networking - ConnectionHealth) Resuming connection check from Suspension
[09.07.2021 12:31:57.938] (networking - ConnectionHealth) ConnectionHealth activated
[09.07.2021 12:32:02.331] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:32:02.331] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:32:02.331] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:32:03.183] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:32:03.183] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:32:03.183] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:32:41.524] (networking - ConnectionHealth) Pausing connection for Suspension
[09.07.2021 12:32:41.524] (networking - ConnectionHealth) ConnectionHealth deactivated
[09.07.2021 12:32:41.524] (networking - PingHelper) PingHelper deactivated
[09.07.2021 12:32:41.921] (networking - ConnectionHealth) Resuming connection check from Suspension
[09.07.2021 12:32:41.921] (networking - ConnectionHealth) ConnectionHealth activated
[09.07.2021 12:32:44.502] (main - MozillaVPN) View log requested
[09.07.2021 12:32:44.510] (main - CloseEventHandler) Add view
[09.07.2021 12:32:44.510] (main - MozillaVPN) Retrieve logs

Mozilla VPN backend logs
========================

2021-07-09, 12:30:01 PM Central Daylight Time - App version: 2.3.0 (2.202105271231); Go backend version: 0.0.0
2021-07-09, 12:30:01 PM Central Daylight Time - Starting tunnel from the OS directly, rather than the app
2021-07-09, 12:30:02 PM Central Daylight Time - DNS64: mapped 68.235.43.106 to itself.

==== SETTINGS ====
devices -> <Sensitive>
gleanEnabled -> true
iapProducts -> org.mozilla.ios.FirefoxVPN.product.1_month_subscription
installationTime -> 2021-07-04T10:00:42.595
ipv6Enabled -> false
languageCode -> 
nativeIOSDataMigrated -> true
previousLanguageCode -> en-CA
privateKey -> <Sensitive>
publicKey -> arvLz6GwlpkgdXbXoGZltYpVM3P5Q1IlDkJDmBpUGwE=
servers -> <Sensitive>
systemLanguageCodeMigrated -> true
telemetryPolicyShown -> true
token -> <Sensitive>

==== DEVICE ====

Name -> Devil iPhone
ABI -> arm64-little_endian-lp64
OS -> ios
OS Version -> 15.0
APP Version -> 2.3.0
Build ID -> 2.202105271231

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-764)

**Comment by JKingZapata** [comment] 2021-07-21 16:33
A known issue with third-party apps has been reported by Apple

**VPN apps fail to connect if they use a private API that no longer exists in iOS 15. (79164225)**

https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-15-beta-release-notes

**Comment by mbirghan** [comment] 2021-07-21 20:01
I cannot reproduce the issue on iOS 15 beta 3 which is the newest version.

@JKingZapata Since the logs are older would it be possible for the user to update to the newest beta version and check whether that fixes the issue?

**Comment by JKingZapata** [comment] 2021-07-26 20:14
@mbirghan I got a user with this issue on iPad confirming he's on iOS 15.3 build - 15.0 (19A5297e) and procured a more recent set of logs, which I attached. 
[Moz VPN iOS 15 logs 2.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6880944/Moz.VPN.iOS.15.logs.2.txt)

**Comment by mbirghan** [comment] 2021-07-28 12:31
I am now able to reproduce the bug consistently. 
The issue is with wireguard and is a known issue. We will have to keep an eye on this and make sure it is either fixed by apple or wireguard.

cc @bakulf

**Comment by mbirghan** [comment] 2021-08-10 07:59
Using the the latest iOS 15 beta version wireguard I was not able to reproduce this issue anymore.
I will close this for now.

**Closed by mbirghan** 2021-08-10 07:59 UTC
Labels: iOS, prod_bug
