### ISSUE TITLE
[Android] In App Feedback sent not recorded

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1355] opened 2021-07-19 15:43 UTC
#### Affected versions:
* Mozilla VPN 2.4.0 (16262900);

#### Affected Platforms:
* Android 10;

#### Prerequisites:
* Have a FxA account and have an active subscription for Mozilla VPN;
* Have Mozilla VPN app installed on your mobile device;
* Be signed in;
* Have Mozilla VPN opened an in off state;

      1. Steps to reproduce:

1. Go to Settings - Give feedback;
1. Select one of the following rating options: “Very poor”/”Poor”/”Average”/Good” and tap the “Continue” button;
1. Choose a category from the list and then click on the “Submit” button;
1. Access: https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/vpn/feedback and observe the screen.

#### Expected result:
* The feedback sent is correctly displayed on the table.

#### Actual result:
* The feedback sent is not recorded.

#### Notes:
* Reproducible 9 out of 10 times.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-747)

**Comment by bakulf** [comment] 2021-07-19 15:44
@madalincm can you upload a log? Thanks!

**Comment by bakulf** [comment] 2021-07-19 15:44
@mbirghan do you have time to work on this?

**Comment by mbirghan** [comment] 2021-07-19 15:47
I will take a look at it

**Comment by madalincm** [comment] 2021-07-21 09:20
Verified this on Mozilla VPN 2.4.0 (2.202107210219), while using Android 10, and it seems that I don't reproduce this anymore, so for now I will close this issue.

**Comment by mbirghan** [comment] 2021-08-31 16:37
Closing this since it cannot be reproduced.

**Closed** 2021-08-31 16:37 UTC
Labels: bug, android, verified, qa_normal, qa_minor
