### ISSUE TITLE
VPN Sign-in issue on mobile with v2.8.0

### ISSUE THREAD

**Issue by edwindubon** [mozilla-mobile/mozilla-vpn-client#3373] opened 2022-04-25 16:47 UTC
**Description**

Users are unable to sign in on the Mozilla VPN app 2.8 log-in workflow.

These users are able to log in using the same email address and password on [accounts.firefox.com](http://accounts.firefox.com/).

**Technical Information**

**Platforms:**
iOS 15.4
Android 12.0
FX product Mozilla VPN 2.8.0

**Steps to Reproduce**
1. Open the Mozilla VPN app
2. Click/tap on "Already a subscriber?" or "Sign up"
3. Enter your email address and password

**Actual Results**

The app takes the users back to writing/typing down their email address, and not signing in to the VPN app.

**Expected Results**

The app should let the users log in with their correct email address and password.
[MozillaVPN-logs.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/8556473/MozillaVPN-logs.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2124)
┆author: Data Sync

**Comment by bakulf** [comment] 2022-04-26 11:53
What I see here is the following:
1. the user is trying to authenticate using a secondary email address
2. we end up showing an error message.
3. The user tries again and again with the same email address and FxA blocks the account for 15 minutes.

The same flow should happen on the web too. We need more data. How many users are reporting this issue?

**Comment by data-sync-user** [comment] 2022-04-26 13:12
➤ Magdalena Schwaighofer commented:

Hey hey

We have 13 users attached to our Trello card now with the same issue : they keep entering the email address, then get redirected to enter the password, then it asks them to enter the email address again in circles

The email address entered is always the one associated with the VPN subscription (as far as we can see in Stripe) 

I also have a video from a user who tries to login with their email address that shows the problem, I will attach it to my comment

the issue is the exact same for 3 of their devices: Samsung A41 with (Android 11), Samsung Galaxy Tab S7, (Android 12), iPad 6th gen (iOS 15.4.1) - the VPN version 2.8 was installed to the phone directly instead of updated from 2.7.1

the only device without this issue is their Fairphone (Android 10) they had mozilla vpn version 2.7.0 installed and then updated to 2.8.0
(I will ask for logs from their working Android vs. the ones with the sign in issue)

here is the video:

!VID_20220425_141407 (1).mp4|width=320,height=480!

**Comment by data-sync-user** [comment] 2022-04-26 18:41
➤ Manuel Calidonio commented:

To add more details to the comment below. Here are logs from a user on an Android device encountering the same behavior when trying to log in using the same email attached with their subscription. 

[^MozillaVPN_Logs_2022-37-26-18-37-48 (1).txt]

**Comment by data-sync-user** [comment] 2022-04-27 01:42
➤ Andrea Marchesini commented:

Do these users see an error message saying “Primary account email required for sign-in”?

**Comment by data-sync-user** [comment] 2022-04-28 05:13
➤ Andrea Marchesini commented:

STR:

  1. have an existing fxa account
  2. Add a secondary email address
  3. Set this secondary email address as the primary one
  4. Try to authenticate using the new primary email address
  5. With the latest fix, the auth will work. With previous versions, it will not

**Comment by data-sync-user** [comment] 2022-05-03 10:50
➤ Valentina Virlics commented:

QA investigated this issue in order to identify why we were not able to encounter it before release.

Conclusions:

  * The issue was not reproducible on the first 26 builds of Mozilla VPN 2.8.0;
  * Not having a single build on which to run all our tests, caused this issue to be missed;

Other details in the following +doc+ ( https://docs.google.com/spreadsheets/d/1A65ajIfdI_zfqfLoenqmewlCH2GlWQc1LynGUmdf_U8/edit#gid=0 ).

Action item: provide a unic build/platform on which QA to run the entire suite.

**Comment by data-sync-user** [comment] 2022-05-03 11:16
➤ Valentina Virlics commented:

Verified this as fixed on Android 10 while using Mozilla VPN 2.8.2 (16512410) and 2.9.0 (16515480), user is able to log in with success while using a primary email (that was initially secondary);

We do not have a build that contain the fix for iOS platform.

Moving this into blocked.

Andrea Marchesini

**Comment by data-sync-user** [comment] 2022-05-03 13:52
➤ Valentina Virlics commented:

Verified this as fixed on the iOS 15.4.1 platform, using Mozilla VPN 2.8.2 (2.202205031449) build. User is able to finalize log in while using a primary email, that was initially secondary.

**Closed by data-sync-user** 2022-05-03 13:52 UTC
