### ISSUE TITLE
VPN client does not launch on Windows

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#6063] opened 2023-02-16 15:48 UTC
**Description**
Some users are reporting that after downloading VPN 2.13 the client does not launch or start, nothing happens when they click on the VPN icon and no error message appears. Issue not occurring on 2.12.

Does it impact functionality or aesthetics? Yes
Does this endanger users? What would be compromised and how likely is the threat? No
How annoying is this for affected users? (Think about how much 'in the way' this is, relative to what the user is trying to do) 
Does it degrade the user experience significantly? Yes
Is it legally sensitive? No

**Centrality** 
Core user journey

**Technical Information**

Platform Windows 10
FX product: Mozilla VPN
Version: 2.13
Region/Languages
Network type (Mobile/Wifi/Wired)

**Steps to Reproduce**

1. Create a local windows user account, with a username that contains non-ASCII characters (eg: `Teßt`), and log into it
1. Purchase subscription 
1. Download client and run installation file
1. Click on the Mozilla VPN icon to launch

**Actual Results**
When clicking the VPN client, nothing happens and it is not visible in the foreground or background

**Expected Results**
VPN window should be visible after launching the client.

![width=200,height=183](https://user-images.githubusercontent.com/72564534/219416777-fb251ef4-cfae-4151-886e-528754e13c7d.png)

![width=200,height=183](https://user-images.githubusercontent.com/72564534/219416819-fe2ed3a7-7dae-4320-b85f-400ac2e9879d.png)

![width=200,height=183](https://user-images.githubusercontent.com/72564534/219416837-b5511a6e-0747-4845-9d2d-9911a033325a.png)

[DxDiag.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/10757761/DxDiag.txt)
[DxDiag-1.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/10757762/DxDiag-1.txt)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-4192)

**Comment by data-sync-user** [comment] 2023-02-16 15:52
➤ Juan Zapata commented:

Around 5 users have reported this

**Comment by data-sync-user** [comment] 2023-02-16 17:12
➤ Lesley Norton commented:

Valentina Virlics Are we testing on Windows 10?

**Comment by data-sync-user** [comment] 2023-02-16 17:42
➤ Matt Cleinman commented:

German Windows 10 investigation:

  1. Microsoft doesn’t let you download language packs w/ an active VPN.
  2. Making German (Germany) my preferred language (what our app reads) doesn’t cause crashes - when using it, restarting app, anything I can find.
  3. Windows display language is still English (though apps know I prefer German) - I need to log out and back in for this to be updated, doing that now. I still cannot replicate the crash. I updated to latest version of Windows 10, my language is set to German, and our VPN is working great!

**Comment by data-sync-user** [comment] 2023-02-16 19:31
➤ Valentina Virlics commented:

Lesley Norton yes, Windows 10 and 11. Did not see this.

**Comment by data-sync-user** [comment] 2023-02-17 08:55
➤ Magdalena Schwaighofer commented:

user on Windows sent DxDiag file for VPN version 2.13 

[^DxDiag.txt]

**Comment by data-sync-user** [comment] 2023-02-20 08:00
➤ Magdalena Schwaighofer commented:

attached please find another crash report from user on Windows 

[^DxDiag (1).txt]

**Comment by data-sync-user** [comment] 2023-02-20 14:03
➤ Basti commented:

I fail to reproduce this. Tried both an emulator and a really old laptop. 
A few things to notice: 
From wer the error code is 0xc0000409 which translates to: `STATUS_STACK_BUFFER_OVERRUN`, so we might be able to diff-search this one?

**Comment by data-sync-user** [comment] 2023-02-23 17:33
➤ Sarah Bird commented:

Moving this to a medium as we’re stumped on repro-ing. If anyone has any ideas we’re all ears!! 
Support will keep us posted with ticket volume.

**Comment by data-sync-user** [comment] 2023-05-10 15:33
➤ Juan Carlos Enriquez commented:

Users are still reporting this on 2.14. There has been a total of 21 user reports since 2.13 was released. Support will attempt to collect dxdiag and event logs. Is there anything else we could be asking?

Juan Zapata

**Comment by data-sync-user** [comment] 2023-05-10 15:38
➤ Naomi Kirby commented:

If you encounter a technically savvy user, could you ask them to retrieve the log file for us? If the client is unable to start then you can find the log file at C:/Users/<username>/AppData/Roaming/mozillavpn.txt. There may be some useful information in that file that can assist us in diagnosing the issue.

**Comment by data-sync-user** [comment] 2023-05-16 08:37
➤ Magdalena Schwaighofer commented:

Hi Naomi Kirby . I have received a log file from a user from this folder on v2.14 

[^mozillavpn.txt]

  * please see below

**Comment by data-sync-user** [comment] 2023-05-16 08:48
➤ Magdalena Schwaighofer commented:

Here is another one from a different user on 2.14

[^mozillavpn (1).txt]

**Comment by data-sync-user** [comment] 2023-05-16 16:47
➤ Naomi Kirby commented:

Aha, that gives us a clue. It seems like the problem has to do with the new VPNGlean telemetry module. The client terminates with the following fragment of log data:

[15.05.2023 15:25:33.702] (Glean) Debug: Initializing VPNGlean
[15.05.2023 15:25:33.703] (Rust) Error: Invalid UTF-8 was passed to rust! Utf8Error { valid_up_to: 10, error_len: Some(1) }cc: Beatriz Rizental Machado

**Comment by data-sync-user** [comment] 2023-05-16 18:33
➤ Naomi Kirby commented:

I have a hypothesis. Windows has its own 8-bit character encoding (CP-1251) which is generated by QString::toLocal8Bit() on Windows, but Rust only accepts UTF-8. Normally, this difference in encoding goes unnoticed because both are supersets of ASCII. However, both of these users have usernames containing non-ASCII characters, this results in an invalid UTF-8 string being generated for the glean directory path, but only on Windows.

**Comment by data-sync-user** [comment] 2023-05-16 19:13
➤ Naomi Kirby commented:

Yep, I can reproduce this by creating a new user account named Teßt on my Windows machine

**Comment by data-sync-user** [comment] 2023-05-23 15:04
➤ Naomi Kirby commented:

This is an excellent use case for some automated test coverage.

**Comment by data-sync-user** [comment] 2023-05-23 15:05
➤ Naomi Kirby commented:

Matt Lichtenstein  We may want to consider this for an uplift to 2.15.0

**Comment by data-sync-user** [comment] 2023-05-23 15:13
➤ Matt Lichtenstein commented:

Naomi Kirby If you believe this would block the 2.15 release, go ahead and uplift! 

cc: Valentina Virlics Bianca Hidecuti Santiago Andrigo Betty Fleming

**Comment by data-sync-user** [comment] 2023-05-24 09:48
➤ Valentina Virlics commented:

Matt Lichtenstein Thank you for the heads up! 

Unfortunately, as we were not been able to reproduce this on our devices, we cannot check to see if this is fixed.

We will smoke check the build to see if still works.

**Comment by data-sync-user** [comment] 2023-05-24 17:27
➤ Naomi Kirby commented:

Valentina Virlics to reproduce this issue you need a Windows machine and a user account name that contains non-ASCII characters. I will update the steps-to-reproduce accordingly.

**Comment by data-sync-user** [comment] 2023-05-25 09:45
➤ Robert Vass commented:

Managed to test this on a device with Windows 11. The issue still reproduces using 2.15.0 (2.202305231701). 

!Screenshot 2023-05-25 122648.png|width=542,height=275!

[^mozillavpn (50da5a86-003a-419e-a610-545e101ecd73).txt]

**Comment by data-sync-user** [comment] 2023-05-25 15:06
➤ Naomi Kirby commented:

So this was uplifted to 2.15.0 yesterday, but unfortunately, I failed to cleanly resolve some merge conflicts during the cherry pick, which resulted in a failure to produce new builds, so I am afraid the fix technically hasn’t made it onto the release branch.

I have started a new PR #6990 ( https://github.com/mozilla-mobile/mozilla-vpn-client/pull/6990 ) to resolve the build error and generate builds again, but we will need to hear from Santiago Andrigo to decide how to proceed with this issue and whether we should fix it or stick with the current RC that doesn’t include the fix.

**Comment by data-sync-user** [comment] 2023-05-26 16:32
➤ Naomi Kirby commented:

As discussed in today’s standup, I am going to revert this change on the 2.15 branch and we will stick with the current RC

**Comment by data-sync-user** [comment] 2023-06-09 11:19
➤ Bianca Hidecuti commented:

Verified this as fixed on Mozilla VPN 2.16.0 (2.202306071820), using Windows 11, while having an user account name that contains non-ASCII characters (tést ß).

The client is now launching after installation.

Attaching postfix video.

!bandicam 2023-06-09 13-26-02-787.mp4|width=1824,height=1068!

**Closed by data-sync-user** 2023-06-09 11:19 UTC
Labels: bug
