### ISSUE TITLE
[foxfooding] Updated the VPN app to version 2.9 and during the update it closed Firefox

### ISSUE THREAD

**Issue by pdehaan** [mozilla-mobile/mozilla-vpn-client#4241] opened 2022-08-22 22:25 UTC
Updated the VPN app to version 2.9 and during the update it closed Firefox. This was unexpected and it didn't bring the session back up once the update completed. It wasn't an issue for me because I have the "open previous windows and tabs" option selected in FF but could be an issue for people who don't. The update prompt doesn't really mention this as a possibility

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2716)

**Comment by bakulf** [comment] 2022-08-24 06:04
It seems a Firefox issue.

**Comment by data-sync-user** [comment] 2022-08-24 09:27
➤ Valentina Virlics commented:

We also had trouble in the past, with Firefox while VPN was ON or changing states, some pages did not load or Firefox closed. But we also had other settings that I think you do not have. More details in here: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1403#issuecomment-913569972 ( https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1403#issuecomment-913569972|smart-link )

**Comment by data-sync-user** [comment] 2022-09-11 19:46
➤ Andrea Marchesini commented:

This is a known issue. See https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1162 ( https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1162|smart-link )  and https://bugzilla.mozilla.org/show_bug.cgi?id=1624546 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1624546|smart-link )

**Comment by data-sync-user** [comment] 2022-09-12 18:25
➤ Santiago Andrigo commented:

Andrea Marchesini So the logic here is that when the Mozilla VPN updates, it uninstalls a DLL that Firefox needs (but that they don’t ship with for some reason), thus crashing it, and that when the VPN is installed again, Firefox is able to use the DLL again?

**Comment by data-sync-user** [comment] 2022-09-12 18:36
➤ Andrea Marchesini commented:

This is correct. More precisely, the mozilla VPN client needs the VC runtime dll and it is installed during the installation phase as the MS documentation says to do. Somehow Firefox, after this installation, starts using the VPN dll. When the client is uninstall, Firefox breaks.

Note that this is not a bug in the VPN client. Other products installing the same DLL can trigger the same issue.

This is a bug in Firefox and there was a PR too, but nobody is working on it. We should ask Firefox to prioritize this bug.

**Comment by data-sync-user** [comment] 2022-09-12 18:53
➤ Santiago Andrigo commented:

Thanks! Pinged Firefox on that bug so that they know this is still happening. Closing this one.

**Comment by data-sync-user** [comment] 2022-09-12 18:54
➤ Santiago Andrigo commented:

Needs to be addressed by Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1624546

**Closed by data-sync-user** 2022-09-12 18:54 UTC
