### ISSUE TITLE
“Language” screen is freezing when dragging the screen to a second monitor

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1226] opened 2021-06-23 09:50 UTC
h4. Affected versions:
* Mozilla VPN 2.4.0 (2.202106162202);
* Mozilla VPN 2.3.2 (2.202106171826);
* Mozilla VPN 2.3.2 (2.202106171827);

h4. Affected Platforms:
* MacOS Big Sur 11.4;

h4. Prerequisites:
* Have a FxA account and have an active subscription for Mozilla VPN;
* Have Mozilla VPN app installed on your device;
* Have an external monitor connected to your Mac.

h4. Steps to reproduce:
# Open Mozilla VPN app and login with the account from prerequisite;
# Move the window to the external monitor;
# Navigate to the Settings screen;
# Click on the Language option;
# Click on any button/option from the screen displayed;
# Observe the screen behaviour.

h4. Expected result:
* The user is able to select the desired language or to switch the button placed on the right side of the “Use system language” text.

h4. Actual result:
* The screen is freezing and the user is not able to select any of the options displayed on the screen.

h4. Notes:
* If the window is dragged back to the first monitor, there in no more freezing;
* Not reproducing on Windows.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-30)
┆author: Data Sync

**Comment by lesleyjanenorton** [comment] 2021-07-15 17:43
@bakulf @mbirghan  Any thoughts on what could be happening here? I'm puzzled.

**Comment by mbirghan** [comment] 2021-07-15 19:19
I narrowed it down to this line being the issue: https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/src/commands/commandui.cpp#L424

If I remove the line the VPN does not freeze. But if I leave it in it also does not seem to block the execution as I can step through the code while the UI is frozen.
Maybe @bakulf knows more about how `QQmlApplicationEngine` works to find the problem.

**Comment by lesleyjanenorton** [comment] 2021-09-07 23:02
@madalincm are you still able to reproduce this? If so, would you mind filing a new issue reflecting that all screens, and not just the languages screen, are affected when using a second monitor? Thank you!

**Comment by flozia** [comment] 2021-09-08 09:12
I can reproduce this on macOS Big Sur 11.5 — the VPN freezes when trying to change the locale while having the VPN on an external monitor.

**Comment by data-sync-user** [comment] 2022-10-31 17:54
➤ Sarah Bird commented:

We have a collection of known issues around external monitors.

**Comment by data-sync-user** [comment] 2022-10-31 17:55
➤ Sarah Bird commented:

Florian Zia Valentina Virlics is this currently reproducing?

**Comment by data-sync-user** [comment] 2022-10-31 18:11
➤ Florian Zia commented:

Sarah Bird I’m not able to reproduce the issue anymore on my side.

**Comment by data-sync-user** [comment] 2022-11-01 08:52
➤ Andrea Marchesini commented:

This was probably fixed by the introduction of Qt6

**Closed by data-sync-user** 2022-11-01 08:52 UTC
Labels: bug, macos, qa_normal, qa_minor

**Comment by data-sync-user** [comment] 2022-11-01 09:05
➤ Bianca Hidecuti commented:

I am also not able to reproduce the issue anymore on Mozilla VPN 2.11.0 (2.202210270603), using MacOS 11.6 and an external monitor.

Attaching a video as well. 

!Screen Recording 2022-11-01 at 11.01.31.mov|width=1298,height=972!
