### ISSUE TITLE
VPN fails to connect on iOS when using cellular network

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#5127] opened 2022-12-05 16:40 UTC
**Description**
iOS users on VPN 2.11 and 2.11.1 are unable to connect to the VPN when using a cellular network (4G or 5G) regardless of server selected. When tapping switch to turn On, it is stuck in "attempting to confirm connection" and after about 5 sec it automatically goes to Off state. Users report that the issue does not happen while using WiFi.  Tried without success reinstalling VPN, port53 and resetting device network settings.

Does it impact functionality or aesthetics? Yes
Does this endanger users? What would be compromised and how likely is the threat? Having the VPN off leaves users data exposed unless they are connected to WiFi
How annoying is this for affected users? (Think about how much 'in the way' this is, relative to what the user is trying to do). Very
Does it degrade the user experience significantly? Yes
Is it legally sensitive? No

**Centrality** 
Is it on a core user journey or on a secondary one? **core journey**

**Connection, Server selection, Adding/removing device, Sign in/out = Core functionality.** 
**Tips & Tricks, Split Tunneling, Printing (Local Network Access), DNS, = Secondary functionality**

**Technical Information**

Platform iOS 16.1 - 16.1.2
FX product Mozilla VPN
Version  2.11 and 2.11.1
Region/Languages
Network type: Mobile

**Steps to Reproduce**

1. purchase subscription and install VPN
1. complete setup
1. have device connected only to a cellular network
1. select any server location
1. tap switch to turn On

**Actual Results**

What happens when following the steps above

* VPN displays "attempting to confirm connection" and disconnects shortly after

**Expected Results**

* VPN should connect regardless of using cellular or WiFi

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-3438)

**Comment by data-sync-user** [comment] 2022-12-05 19:39
➤ Gela Malek Pour commented:

I am not able to reproduce this issue on my iPhone. The VPN seems to connect as expected.

VPN: 2.11.1

iOS: 16.1

!IMG_0644.png|width=1170,height=2532,alt="screenshot of VPN running on my phone"!

**Comment by data-sync-user** [comment] 2022-12-05 20:30
➤ Gela Malek Pour commented:

Sarah Bird

**Comment by data-sync-user** [comment] 2022-12-05 21:12
➤ Sarah Bird commented:

Juan Zapata how many users do you currently have affected by this?

**Comment by data-sync-user** [comment] 2022-12-05 21:12
➤ Sarah Bird commented:

assigning to Matt Cleinman for triage

**Comment by data-sync-user** [comment] 2022-12-05 22:59
➤ Matt Cleinman commented:

I can replicate this, no need for additional logs. Thank you for those initial logs.

Diagnosis so far: For some reason the forked repo didn’t propagate through to the app, and so we’re still using the buggy lines in `IPAddress+AddrInfo.swift`. Currently investigating what happened, but it’s likely we’re going to want to do another dot release for this one.

**Comment by data-sync-user** [comment] 2022-12-07 18:58
➤ Matt Cleinman commented:

I’ve confirmed that this is fixed on TestFlight (2.12.0, build 2844).

**Comment by data-sync-user** [comment] 2022-12-07 20:32
➤ Juan Zapata commented:

In case it is relevant we have a user on iOS 15.6 reporting this issue. Attaching the logs if they need to be reviewed. 

[^MozillaVPN-logs-7.txt]

**Comment by data-sync-user** [comment] 2022-12-09 09:43
➤ Bianca Hidecuti commented:

QA is not able to verify this scenario as we are not able to connect to the internet while using cellular data on our testing devices.

**Comment by data-sync-user** [comment] 2022-12-14 17:29
➤ Matt Cleinman commented:

I verified it on TestFlight, so I feel fairly confident on it. I believe that yes, we can move this to Done. Moving it now.

**Closed by data-sync-user** 2022-12-14 17:29 UTC
Labels: bug

**Comment by data-sync-user** [comment] 2022-12-14 17:46
➤ Santiago Andrigo commented:

Great! I also added the 2.12 fixVersion.
