### ISSUE TITLE
Consider adding a "Check for Update" button in the settings

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#1701] opened 2021-09-02 10:51 UTC
So I just had a conversation on matrix where a user was not shown the update prompt and was asking if there is an option to manually trigger a recheck. 
Maybe we could add an info text below the version "you're on the latest version // link to update view" and a button to manually trigger the check-version task :grinning:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-941)

**Comment by data-sync-user** [comment] 2021-12-02 11:14
➤ Madalin Cotetiu commented:

Verified this as fixed on Mozilla VPN:

  * 2.7.0 (2.202112020832), while using MacOS Big Sur 11.6;
  * 2.7.0 (2.202112020837), while using Windows 10;
  * 2.7.0 (16384340), while using Android 10;

“Check for Updates” button is displayed in the Settings - About us screen. 

Note: The two circular arrows icon form the “Check for updates” button is displayed on the left side of the button on Mozilla VPN, whereas on Figma files the icon is displayed just before the “Check for updates” text - is this an issue, Sebastian Streich ?

**Comment by data-sync-user** [comment] 2021-12-13 10:55
➤ Sebastian Streich commented:

Madalin Cotetiu - Yes that was intended by me, as there is a limitation on our button-component where i can place those things 🙈

**Comment by data-sync-user** [comment] 2021-12-13 11:07
➤ Madalin Cotetiu commented:

Ok, Thanks.

**Closed by data-sync-user** 2021-12-13 11:07 UTC
Labels: enhancement, verified, UX
