### ISSUE TITLE
Unable to connect to printer with local network access selected

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#2060] opened 2021-10-18 21:49 UTC
**Description**
Users cannot use printer or other devices that need access to local network when connected to VPN even though the local network access option is selected.

**Technical Information**

* Platform: Windows 10
* FX product Mozilla VPN 2.5

**Steps to Reproduce**

1. Have an active VPN subscription
2. Download/install VPN
3. enable Local network access from VPN network settings
4. attempt to connect to device from local network

**Actual Results**
Printer and other devices do not connect until VPN is turned off.

[mozillavpn-2021-10-16.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/7368704/mozillavpn-2021-10-16.txt)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1179)

**Comment by data-sync-user** [comment] 2021-10-20 14:34
➤ Owen Kirby commented:

This should be fixed by PR #2065, which excludes the multicast address ranges when local network access is enabled.

**Comment by data-sync-user** [comment] 2021-11-02 14:55
➤ Valentina Virlics commented:

Verified again on Windows 10, using the last VPN build 2.6.0 (2.202111011425), and the result are exactly like mentioned below.

Note: not reproducing on Mac OS.

Owen Kirby

**Comment by data-sync-user** [comment] 2021-11-05 19:01
➤ Marcus Kestler commented:

An update on what I have found on this issue so far.

  1. The printer is temporarily offline.  It will come back online in roughly 1-3 minutes with the VPN on.
  2. It will sporadically go offline and back online while the connection is up.

I looked at this in wireshark.  What I see is the MDNS (what windows uses for printer and device connections) is disconnection from it’s multicast group on VPN connections.  It then tries to rejoin, but at that time the printer does not respond.  Other devices do, such as my NAS, Router, etc.  After some random interval the printer will eventually respond.

I wrote code to manually query MDNS after the connection start to try to reestablish the connection.  I did specific queries for printers.  This had no effect (I did see the queries go over the wire, but still no response from the printer)

I have looked at all of our multi-cast address exclusions and tunnel setup.  It appears fine.

Next I downloaded the Mullvad VPN client to see if it was in the driver perhaps.  The Mullvad client has the same behavior as ours.  (You set Local Network Access in preferences in their client).

The Mullvad readme has some noted limitation on multicast:  https://github.com/mullvad/win-split-tunnel ( https://github.com/mullvad/win-split-tunnel|smart-link ) 

The section on multicast reception seems of interest, but I don’t understand why it would fail only on the printer, and not other devices…

At this point, I don’t have a lot of other ideas to look at unless I start digging in to the Mullvad driver.

**Comment by data-sync-user** [comment] 2021-11-17 16:43
➤ Rebecca Billings commented:

Marcus Kestler are there any updates for this?

**Comment by data-sync-user** [comment] 2021-11-17 17:01
➤ Marcus Kestler commented:

Rebecca Billings This is blocked for the foreseeable future.  I’ve been told to give it low priority.

**Comment by data-sync-user** [comment] 2021-12-23 17:15
➤ Brian Yee commented:

Marcus Kestler Can you follow up with Mullvad on this in the new year?  Support is seeing issues and I can repro consistently on Windows.

**Comment by data-sync-user** [comment] 2022-04-18 13:09
➤ Luminita Buruian commented:

Verified as fixed on Mozilla VPN 2.8.0 (2.202204071125), on MacOS 12.3.1

The printer can successfully be used while connected to the VPN.

CC: Valentina Virlics

**Closed by data-sync-user** 2022-04-18 13:09 UTC

**Comment by data-sync-user** [comment] 2022-04-20 15:23
➤ Joseph Anthony Cuevas commented:

Luminita Buruian Was this tested on Windows as well since the issue was reported on Windows?

**Comment by data-sync-user** [comment] 2022-04-20 17:21
➤ Sebastian Streich commented:

Played with this a bit, i can seem to reproduce even when the Split-Tunnel driver is turned off  

:c

!image-20220420-172038.png|width=448,height=298!

**Comment by data-sync-user** [comment] 2022-04-21 06:27
➤ Luminita Buruian commented:

Hello Joseph Anthony Cuevas 

Yes, this was also tested on Windows 10, using Mozilla VPN 2.8.0 (2.202204071128) signed build.

Although it took about 5 minutes to first connect, due to an instable connection, on the second try the printer was online and worked as expected.

Please let us know if there is anything else we need to check in this case.

CC: Valentina Virlics
