### ISSUE TITLE
[foxfooding] When turning on the VPN, the app briefly shows that its attempting to connect, and then immediately disconnects and all network connectivity is lost on the Windows machine

### ISSUE THREAD

**Issue by pdehaan** [mozilla-mobile/mozilla-vpn-client#4238] opened 2022-08-22 22:22 UTC
When turning on the VPN, the app briefly shows that its attempting to connect, and then immediately disconnects and all network connectivity is lost on the Windows machine, and the VPN app shows "VPN is off". At this point I'm unable to connect to the VPN and internet no longer works on the Windows machine. To fix my internet, I need to restart the machine.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2719)

**Comment by oskirby** [comment] 2022-09-14 15:37
Hey @pdehaan sorry for the delay on this issue, I don't suppose you would be able to share your log files after attempting to connect the VPN? We have seen a rare few instances of the VPN client failing to connect but the persistent internet breakage after the VPN returns to an off state is unusual.

This suggests that there is something different happening in your situation.

**Comment by data-sync-user** [comment] 2022-10-05 08:30
➤ Bianca Hidecuti commented:

Hi Peter deHaan ,

Could you please give us more details regarding the occurrence of this issue?

QA was not able to reproduce this on 2.9 and 2.10 versions, while using Windows 10/11. 

Thank you!

**Comment by pdehaan** [comment] 2022-10-05 14:18
Ah, sorry, I missed this earlier ping...
This was from foxfooding, so I'll have to find the spreadsheet and see if I can find you the name of the original reporter and you can reach out to them (since the entirety of my knowledge is a rushed copy-paste of the report above). @oskirby I'll DM you shortly in Slack.

**Comment by data-sync-user** [comment] 2022-10-05 16:25
➤ Santiago Andrigo commented:

FYI that the reporter just confirmed to me that this happens consistently for him (which in my mind equates to it being likely caused by a local setup).

**Comment by data-sync-user** [comment] 2022-10-05 16:53
➤ Reino Muhl commented:

Reporter here, in case it helps, I’ve created a Support ticket with number 77218.

**Comment by data-sync-user** [comment] 2022-10-05 16:54
➤ Santiago Andrigo commented:

Joseph Anthony Cuevas would you mind fishing out and attaching the logs from the support ticket that Reino just created please?

**Comment by data-sync-user** [comment] 2022-10-10 16:33
➤ Santiago Andrigo commented:

Updating this to “low” based on Joe’s comment and that the severity of this bug is so extreme that if it were widespread we would know about it.

**Comment by data-sync-user** [comment] 2022-10-10 17:24
➤ Josh Schrader commented:

To clarify Joe’s statement: Reino Muhl is still experiencing the issue, but no other support tickets were unable to be resolved with basic troubleshooting. 

From Reino: “Hi Josh. It happens consistently and every time I do it. Basically on my Windows 10 box, I can’t use Mozilla VPN.”.

After a longer conversation with Reino on slack and looking at the logs, I have been unable to determine what is causing the VPN to fail on (only) his machine. I think we may need more logging or possibly even local debugging on the affected machine to determine the cause.

**Comment by data-sync-user** [comment] 2023-05-26 14:51
➤ Lesley Norton commented:

Closing in favor of VPN-4253, which is in progress.

**Closed by data-sync-user** 2023-05-26 14:51 UTC
