### ISSUE TITLE
VPN app update to latest version is not working as expected

### ISSUE THREAD

**Issue by LuminitaB** [mozilla-mobile/mozilla-vpn-client#1328] opened 2021-07-15 08:36 UTC
#### VPN version:
- 2.3.0 (2.202105270956);
- 2.3.2 (2.202107091528);

#### Affected Platforms:
- MacOS Catalina 10.15.7;

#### Prerequisites:
- Have one FxA account with subscription;

#### Steps to reproduce:
1. Install an older version of the Mozilla VPN (in this case 2.3.0);
2. Log in with the account mentioned in the Prerequisites;
3. Click on the Update banner;
4. From the Update screen, click on “Update now”;

#### Expected result:
- The update to 2.3.2 is done successfully;

#### Actual result:
- The screen is blocked, the loading wheel is present but the update is not performed. The “Update now” button is re-enabled after a few seconds.
Clicking on it several times triggers the same behavior each time

#### Note:
- Signing out, quitting the app and doing the process over again, seems to trigger the update correctly and it is performed successfully.
- Please see the app logs attached.

[mozillavpn-2021-7-15.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6821546/mozillavpn-2021-7-15.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-724)

**Comment by bakulf** [comment] 2021-07-15 13:48
Are you trying to update version 2.3.0 prod or staging? It seems production because balrog is not updated in staging.

**Comment by ValentinaPC** [comment] 2021-07-15 14:09
Production, yes.

**Comment by ValentinaPC** [comment] 2021-08-24 13:45
I've managed to update from 2.3.2 to 2.4.1, while using Windows 10 x64.
I'll let Lulu confirm on Mac OS.

**Comment by LuminitaB** [comment] 2021-08-24 13:57
I have just tried an update on MacOS Catalina 10.15.7 from 2.3.0 to 2.4.1 and the behavior is still the same as described in the above.

**Comment by data-sync-user** [comment] 2021-12-17 13:36
➤ Andrea Marchesini commented:

We run 2.7. No issue has been founded yet. Let’s close this bug.

**Comment by data-sync-user** [comment] 2021-12-20 12:02
➤ Valentina Virlics commented:

Verified this on the last VPN 2.7.0 (2.202112170222) build on Windows 10.

Attaching the logs from the Inspector, while trying to make a recommended update.

[^mozillavpn.txt]

**Comment by data-sync-user** [comment] 2021-12-21 22:36
➤ Owen Kirby commented:

So, in this scenario. Version 2.7.0 of the client is installed, but the latest and greatest that has been uploaded to Balrog is 2.6.x. Perhaps we should be asking what the expected behaviour is here when triggering the forced update when we are already running the latest version. The sequence of events shown in the logs is as follows:

  1. An inspector command is issued to force an update.
  2. Balrog is queried and the version is faked to be v1.5, because this is triggered by the inspector.
  3. The latest and greatest build of the client is downloaded (2.6.0).
  4. The 2.7.0 version of the client validates the signature, and launches the installer.
  5. The installer detects that it would install version 2.6.0 over 2.7.0. Since this is a downgrade, the installer exits with an error.

There doesn’t really appear to be a bug here, but this issue continues to linger. Perhaps we need better error messaging about the downgrade, or maybe we should permit the downgrade anyways to facilitate testing.

**Comment by data-sync-user** [comment] 2021-12-22 13:21
➤ Valentina Virlics commented:

From QA perspective, we need to come up with a solution to be able to test self-update for each release, as it is the main functionality that old VPN users will face.

So, removing that downgrade restriction, or having always the last version number on Balrog, anything is easier or can be done, works for us, as long as we can check and finalize the self-update.

**Comment by data-sync-user** [comment] 2022-11-01 09:10
➤ Andrea Marchesini commented:

Valentina Virlics can we close this?

**Comment by data-sync-user** [comment] 2022-11-01 14:56
➤ Valentina Virlics commented:

Sure, but we can  also improve the current process going forward.

**Closed** 2022-11-01 14:56 UTC
Labels: bug, macos, qa_normal
