### ISSUE TITLE
[foxfooding] Cannot paste email or password into the input fields when trying to log into my Firefox account on the iPhone app

### ISSUE THREAD

**Issue by pdehaan** [mozilla-mobile/mozilla-vpn-client#3692] opened 2022-06-06 23:30 UTC
I cannot paste email or password into the input fields when trying to log into my Firefox account on the iPhone app; no standard options like copy, paste, etc. appear when I press on the input field. I use a separate password manager app, and I find it inconvenient to manually input credentials, especially for long randomly generated passwords

When I experienced this, when tapping on the input field (to try and bring up the context menu for pasting), it simply played the "keyboard popping up" animation as if I defocused away from the field and then back.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2365)

**Comment by data-sync-user** [comment] 2022-06-06 23:41
➤ Peter deHaan commented:

Row 24 in https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0 ( https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0|smart-link )

**Comment by data-sync-user** [comment] 2022-06-07 11:56
➤ Maria Berlinger commented:

Thank you for logging this. The issue is already tracked here: https://mozilla-hub.atlassian.net/browse/VPN-1812 ( https://mozilla-hub.atlassian.net/browse/VPN-1812|smart-link )

**Comment by data-sync-user** [comment] 2022-06-29 00:18
➤ Lesley Norton commented:

Closing as duplicate of VPN-1812

**Comment by data-sync-user** [comment] 2022-06-29 00:18
➤ Lesley Norton commented:

Thank you Maria Berlinger . Closing as dupe.

**Closed** 2022-06-29 00:18 UTC

**Comment by data-sync-user** [comment] 2023-01-23 03:40
➤ Santiago Andrigo commented:

.
