### ISSUE TITLE
UI nit - "Signed out and device removed" 

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#907] opened 2021-04-27 18:42 UTC
Hi, if you sign in with FXA but don't have a subscription. If you then sign out, then the message reads "signed out and device removed." 

I think technically speaking this may actually be correct because adding a device is a two part process on the guardian side of things. (That's a separate issue we could clean up.)

But I'm wondering if the "device removed" part is confusing if you didn't get as far as being authed in and see the list of devices.

**Comment by rbillings** [comment] 2021-04-27 18:45
This is a duplicate of https://github.com/mozilla-mobile/mozilla-vpn-client/issues/780

**Closed** 2021-04-27 19:05 UTC
