### ISSUE TITLE
VPN client suddenly turns off on Android (2.12)

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#5483] opened 2023-01-09 17:19 UTC
VPN client on Android suddenly appears to be switched off without any notice. Users may notice an icon on the device status bar that the VPN is still On and confirm that the device is still protected by doing a Mullvad check [https://mullvad.net/en/check/](https://mullvad.net/en/check/).  The issue has been recurring since V 2.10. Filing bug again. Original Jira bug [https://mozilla-hub.atlassian.net/browse/VPN-3208](https://mozilla-hub.atlassian.net/browse/VPN-3208|smart-link)

Does it impact functionality or aesthetics? Yes, aesthetics
Does this endanger users? What would be compromised and how likely is the threat? No
How annoying is this for affected users? (Think about how much 'in the way' this is, relative to what the user is trying to do) Yes, users believe they are no longer protected by the VPN
Does it degrade the user experience significantly? Yes
Is it legally sensitive? No

**Centrality** 
Is it on a core user journey or on a secondary one? 

* Core user journey

**Technical Information**

Platform Android 11
FX product Mozilla VPN
Version 2.12
Region/Languages
Network type Mobile/Wifi

**Steps to Reproduce**

1. purchase subscription
1. install VPN
1. connect to any server location
1. leave VPN On

**Actual Results**

* After an undetermined amount of time, the VPN client appears to be Off without any notice

**Expected Results**

* Client should display On unless it is manually turned off

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-3706)

**Comment by JKingZapata** [comment] 2023-01-09 17:20
Attaching recent logs

[MozillaVPN_Logs_2023-12-09-10-12-13.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/10375440/MozillaVPN_Logs_2023-12-09-10-12-13.txt)

**Comment by data-sync-user** [comment] 2023-01-09 18:30
➤ Santiago Andrigo commented:

Juan Zapata So this is only noticeable if the user opens the client, right? No OS notification?

**Comment by data-sync-user** [comment] 2023-01-12 15:24
➤ Juan Zapata commented:

Santiago Andrigo correct, there is no notification. It is only noticeable when checking the client

**Comment by data-sync-user** [comment] 2023-02-07 07:51
➤ Magdalena Schwaighofer commented:

not sure if this is still helpful (as 2.13 will be released soon) but here is another set of logs for this bug on 2.12

[^MozillaVPN_Logs_2023-27-06-9-27-21.txt]

**Comment by data-sync-user** [comment] 2023-02-13 15:58
➤ Santiago Andrigo commented:

Bumping this to High as this is the biggest issue found in January, as per Joe.

**Comment by data-sync-user** [comment] 2023-02-27 16:24
➤ Santiago Andrigo commented:

Basti , Joseph Hernandez seems to have bumped into this issue on 2.13. The logs are here: https://drive.google.com/file/d/1KPXH47_TsKC5yp9gkYwayF-l5Sl8nOSR/view?usp=share_link ( https://drive.google.com/file/d/1KPXH47_TsKC5yp9gkYwayF-l5Sl8nOSR/view?usp=share_link|smart-link ). Does it look related?

Joseph Hernandez is there any more color that you can add about when it’s happening?

**Comment by data-sync-user** [comment] 2023-02-28 16:29
➤ Joseph Hernandez commented:

Haven’t been able to determine the amount of time it takes for this to occur but I do know that consistently if I don’t see the VPN logo at the top I know I can open the app to reproduce the issue. (Just did it right now)

**Comment by data-sync-user** [comment] 2023-03-08 10:47
➤ Valentina Virlics commented:

QA was not able to reproduce this on 2.12/2.13.

**Comment by data-sync-user** [comment] 2023-03-08 15:15
➤ Santiago Andrigo commented:

Juan Zapata Joseph Anthony Cuevas How is this issue evolving? In January, my understanding was that this was a big deal. Are you able to see if you can see this in 2.13 still?

**Comment by data-sync-user** [comment] 2023-03-08 16:12
➤ Andrea Marchesini commented:

Santiago Andrigo the fix goes in the right direction, but we need to verify the bug to be 100% sure. I cannot give you a 5 of 5 confidence level.

**Comment by data-sync-user** [comment] 2023-03-08 16:32
➤ Santiago Andrigo commented:

Ok, that’s fine. It’s just the nature of the beast when we have non-reproducible bugs. We’ll just have to monitor things. I’m moving this to “Done” as there is no way for QA to verify.

Andrea Marchesini the one possibly wise thing to consider is - should we have this (whatever it is) be implemented behind a feature flag, such that if all hell breaks loose, we can disable this instantly?

**Closed** 2023-03-08 16:31 UTC
Labels: bug

**Comment by data-sync-user** [comment] 2023-03-22 14:08
➤ Juan Zapata commented:

Santiago Andrigo since 2.13.1 was released we’ve seen about 20 user reports, not including Google reviews. We have logs if you need them, but I see this has already been marked as Done, so we will keep an eye on further cases once 2.14 is out.
