### ISSUE TITLE
I do not undestand this problem installing Mozilla VPN using Terminal. Zorin OS 16.1.

### ISSUE THREAD

**Issue by apetivist** [mozilla-mobile/mozilla-vpn-client#3650] opened 2022-06-01 12:03 UTC
Shouldn't the distro be understood as Ubuntu since it is Ubuntu based? Is there any fix for this? I just paid for this Firefox VPN service. Running Zorin OS Pro 16.1 and it is all updated. Windows X11. Any other details will be added upon request.

## I am having this error when attempting to install via Terminal.
[01.06.2022 06:43:21.884] Info: (main - Command) MozillaVPN 2.8.0
[01.06.2022 06:43:21.885] Info: (main - Command) User-Agent: MozillaVPN/2.8.0 (sys:zorin 16)
[01.06.2022 06:43:22.114] Warning: QApplication: invalid style override 'adwaita' passed, ignoring it.
Available styles: Windows, FusionZorin OS Pro 16.1 and it is all updated. Windows X11.

[01.06.2022 06:43:22.120] Error: (main - EventListener) Connection failed.
[01.06.2022 06:43:22.265] Info: (networking - NetworkRequest) Imported cert from: ISRG Root X1
[01.06.2022 06:43:22.282] Warning: QQmlApplicationEngine failed to load component
[01.06.2022 06:43:22.282] Warning: qrc:/ui/main.qml: module "adwaita" is not installed (main.qml)

## Segmentation fault

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2308)

**Comment by birdsarah** [comment] 2022-06-02 16:15
Hi! Thank you for reporting the issue. 

We believe this is a duplicate of https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3367 and so are going to close this issue.

We have a fix in progress https://github.com/mozilla-mobile/mozilla-vpn-client/pull/3558 which should be out in 2.9.

**Comment by data-sync-user** [comment] 2022-06-02 16:17
➤ Sarah Bird commented:

Dupe

**Closed as completed** 2022-06-02 16:17 UTC

**Comment by birdsarah** [comment] 2022-06-03 20:22
@apetivist there is a potential workaround here: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3367#issuecomment-1129291134
