### ISSUE TITLE
German language suggestions

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#934] opened 2021-04-30 17:34 UTC
From DE user feedback: Emails with payment receipt and first steps address user formally while website uses informal style

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-161)
┆author: Data Sync

**Comment by rbillings** [comment] 2021-04-30 17:34
feedback: Login confirmation address user formally while website uses informal style

**Comment by rbillings** [comment] 2021-04-30 17:35
feedback: App address user formally while website uses informal style

**Comment by rbillings** [comment] 2021-04-30 18:00
feedback: Option to cancel subscription is "Abbrechen" and should be "Kündigen" or "Stornieren"

**Comment by data-sync-user** [comment] 2022-10-14 08:38
➤ Andrea Marchesini commented:

Francesco Lodolo is there anything we can do here? If not, we can close this issue.

**Comment by data-sync-user** [comment] 2022-10-14 08:47
➤ Francesco Lodolo commented:

Unfortunately this is not really actionable, also considering several months have passed:

  * It spans over at least 3 different projects (VPN Client, mozilla.org ( http://mozilla.org ), Firefox Accounts?) with different owners. For example, “Abbrechen” doesn’t show up anywhere in the VPN client, it might be from Firefox Accounts, but without a clear way to reproduce it’s impossible to find.
  * Formal vs Informal is probably also expected, because apps normally use formal, while http://mozilla.org ( http://mozilla.org|smart-link ) would more likely use informal (given the target), because that’s what marketing wants.

**Closed** 2023-08-14 22:25 UTC
Labels: L10N
