### ISSUE TITLE
Error "waiting for sign in and subscription confirmation" when logging in.

### ISSUE THREAD

**Issue by jr-johnson-support** [mozilla-mobile/mozilla-vpn-client#965] opened 2021-05-04 20:59 UTC
Users are getting an error "Waiting for sign in and subscription confirmation" after clicking on 'Get started" and trying to sign in to Mozilla VPN

Expected behavior:
install VPN, launch, login, use. 

Actual Results:
After installing and attempting to log in, the user gets stuck with an error attempting to sign in and a loading circle as seen in the images below. The user is stuck in this sign in loop unable to progress pass the loading error notification. 

This issue started with V2.1 
[signinErrorConfirmation.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6423876/signinErrorConfirmation.txt)
[mozillavpn-2021-4-27.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6423884/mozillavpn-2021-4-27.txt)
![signinErrorScrnSht](https://user-images.githubusercontent.com/58608126/117068874-6ebe6780-acf1-11eb-9270-981538f31ed1.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-175)

**Comment by birdsarah** [comment] 2021-05-10 17:07
@jr-johnson-support that log is from an ios device, I thought this was a windows issue.

**Comment by birdsarah** [comment] 2021-05-10 17:27
@jr-johnson-support - the first two logs on this issue (the text files) are from 2.1 can you ask the users to upgrade to 2.2 and see if it's still an issue.

**Comment by ValentinaPC** [comment] 2021-05-12 07:00
Side note: the "Cancel and try again" link, was replaced with only "Cancel" in the last 2.2 builds.

**Comment by birdsarah** [comment] 2021-05-12 16:31
@jr-johnson-support as discussed, some extra info that would be helpful:
* windows version
* the browser that's opening the sign-in window - including the version number
* if you have a very technical user, then the console log from the browser window would be super helpful. the question of "what are the instructions for getting them" is browser specific......

**Comment by jr-johnson-support** [comment] 2021-05-12 16:45
81 tickets tagged for this issue thus far as of 05/12/2021

**Comment by jr-johnson-support** [comment] 2021-05-12 16:50
It seems as though this error is not confined to Windows. This user is running into the same issue on Mac. See the logs attached. user on version 2.2
[macosLogs.odt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6467778/macosLogs.odt)

**Comment by punster-moz** [comment] 2021-05-21 06:48
Regarding macrosLogs.odt, If the version is already 2.2 why does it try to access Balrog to get updated and failed. Also, Is hostname of len 0 normal.

**Comment by oskirby** [comment] 2021-05-21 16:02
This may not be related to the issue that users are reporting, but I've encountered similar problems attempting to sign in on KDE Desktop with Konqueror as the default browser.

**Comment by punster-moz** [comment] 2021-05-21 16:34
Can we identified the error points and add more debug log to isolate the
issue ?

**Comment by jr-johnson-support** [comment] 2021-05-26 16:13
94 tickets noted with this issue. 

[sign-in-issueTicket22311.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6548144/sign-in-issueTicket22311.txt)
[Sign-in-issueTicket22075.odt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6548149/Sign-in-issueTicket22075.odt)

**Comment by jr-johnson-support** [comment] 2021-06-09 13:31
116 tickets as of 06/09

**Comment by jr-johnson-support** [comment] 2021-06-23 14:17
138 tickets submitted to Zendesk since issue arose in 2.2

**Comment by ValentinaPC** [comment] 2021-07-21 12:21
Any updates on this? Thanks!

**Comment by birdsarah** [comment] 2021-07-21 13:14
I've  removed myself as I'm not actively working on this. Last time @lesleyjanenorton and I worked on this we couldn't reproduce.

**Comment by smsunarto** [comment] 2021-08-16 20:40
Was able to reproduce this. Using firefox over chrome to login fixes it.

**Comment by ValentinaPC** [comment] 2021-08-30 09:44
Verified this on v.2.5 (16300130) while using Android 10 and I am not able to end up in VPN activation screen.
- I am blocked in "Waiting for sign in and subscription confirmation..." no matter if I log in with an account with or without subscription.
- Not reproducing on Win or Linux;
- Not reproducing on prod build.
- Observed that might be related with other vpn that is ON on my device.

Attaching logs.
[jmnpdniE.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/7075722/jmnpdniE.txt)

**Comment by JKingZapata** [comment] 2021-11-10 19:56
Attaching set of logs with this symptom unrelated to SSL handshake error

This line of log gets my attention `Error: (networking - NetworkRequest) Network error: Host vpn.mozilla.org not found status code: 0 - body:`

[mozillavpn-2021-10-28.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/7515563/mozillavpn-2021-10-28.txt)

**Comment by data-sync-user** [comment] 2021-11-19 15:36
➤ Juan Zapata commented:

Attaching another set of logs not related to SSL handshake error

[^mozillavpn-2021-11-19.txt]

**Comment by data-sync-user** [comment] 2021-12-17 13:50
➤ Andrea Marchesini commented:

Fixed in 2.5 if I remember correctly.

**Closed by data-sync-user** 2021-12-17 13:50 UTC
Labels: macos, windows, p1, prod_bug
