### ISSUE TITLE
 Hovering on the “Protect all apps with VPN” button displays the same tooltip for both enable/disable states

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1364] opened 2021-07-20 10:50 UTC
- 2.4.0 (2.202107191711);

#### Affected Platforms:
- Linux Ubuntu 20.04;

#### Prerequisites:
- Have one FxA account without subscription;
- Have the VPN installed on your machine;

#### Steps to reproduce:
1. Login to VPN with the account from prerequisites;
2. Go to Settings-> App Permissions;
3. Hover over the switch button for both states;

#### Expected result:
- Different text is displayed according to the enable/disable states;

#### Actual result:
- Same “Protect all apps with VPN” is displayed for both states.

#### Notes:
- Another confusing thing is the text “VPN protects all apps by default. Turn off to choose which apps Mozilla VPN should not protect.” displayed for both states of the feature - having an unprotected app is not visible if the feature is ENABLED.
![image](https://user-images.githubusercontent.com/15685960/126311498-5b017f0f-f0a9-46d8-9484-95e8ce2cd087.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-752)

**Comment by ValentinaPC** [comment] 2021-07-20 10:50
@lesleyjanenorton @strseb The "Select all" option should be available on 2.4? Thanks!

**Comment by bakulf** [comment] 2021-07-20 15:19
@jess-cook03 @peterbenvenuto do we want to have 2 strings for the tooltip? If yes, can you provide them?
We are late for 2.4, they will be included in 2.5.

**Comment by peterbenvenuto** [comment] 2021-07-20 15:55
@bakulf @jess-cook03  I think we explored this and thought it might be confusing to have 2 strings because then we'd have to change the card header as well, but we can explore it again for 2.5 if it ends up being confusing. It follows the same functionality as the language toggle which doesn't change it's language either.

**Comment by ValentinaPC** [comment] 2021-07-23 09:47
Now, with latest builds, the entire text of that section is displayed at hover. not sure what happened. Same text for both states.
![image](https://user-images.githubusercontent.com/15685960/126765234-b2f3b56f-be2a-4999-95f6-4859339d2f7b.png)

**Comment by lloan** [comment] 2022-04-15 19:04
I was able to replicate.

Off state: 
<img width="272" alt="image" src="https://user-images.githubusercontent.com/3924990/163621824-23196774-9c04-4c34-9aa1-e7f5b5d9bb7c.png">

On state: 
<img width="273" alt="image" src="https://user-images.githubusercontent.com/3924990/163621859-c9c63668-f4be-47a6-b5f1-60b8cfeecabc.png">

**Comment by data-sync-user** [comment] 2022-05-30 11:51
➤ Valentina Virlics commented:

Verified this on Windows 10, while using Mozilla VPN 2.9.0 (2.202205291610) build.

The button label at hover is the same.

See below screenshot. Reopening.

!app permissions.png|width=274,height=373!

**Comment by data-sync-user** [comment] 2022-05-31 15:53
➤ Lesley Norton commented:

This is expected behavior I think and consistent with Firefox toggle aria label behavior in about:addons. The aria value does not change based on the toggle's enabled/disabled state. Peter Benvenuto do we want to use separate strings here or leave as is? We could also remove the tooltip altogether.

**Comment by data-sync-user** [comment] 2022-05-31 15:54
➤ Peter Benvenuto commented:

Lesley Norton I don’t think we need different strings and the behaviour is expected.

**Comment by data-sync-user** [comment] 2022-05-31 17:13
➤ Lesley Norton commented:

Cancelling this ticket since this is the expected behavior

**Closed by data-sync-user** 2022-05-31 17:13 UTC
Labels: bug, linux, qa_normal, qa_minor
