### ISSUE TITLE
VPN fails to launch automatically at device restart on Linux and user needs to sign in again.

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#5982] opened 2023-02-09 16:18 UTC
**Description**
Linux users on VPN 2.13 report that the client fails to launch at startup when enabling the "connect VPN at startup" setting. When manually launching the VPN, they must sign in to the client every time.

Does it impact functionality or aesthetics? Functionality 
Does this endanger users? What would be compromised and how likely is the threat? No
How annoying is this for affected users? (Think about how much 'in the way' this is, relative to what the user is trying to do) _It can be very annoying for a user who expects the client to connect automatically._
Does it degrade the user experience significantly? Yes
Is it legally sensitive? No

**Centrality** 
Is it on a core user journey or on a secondary one? 
Secondary functionality**

**Technical Information**

Platform Linux Ubuntu 22.04
FX product Mozilla VPN
Version 2.13
Region/Languages
Network type (Mobile/Wifi/Wired)

**Steps to Reproduce**
1. Install VPN
2. Complete setup and enable "connect VPN on startup" setting
3. Restart device
4. Expect client to launch

**Actual Results**
After device restart, client does not launch and user needs to sign in again.

**Expected Results**
Client should automatically launch and connect on startup with this setting enabled.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-4148)

**Comment by JKingZapata** [comment] 2023-02-09 16:18
[mozillavpn-2023-2-9.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/10699202/mozillavpn-2023-2-9.txt)

**Comment by arnobl** [comment] 2023-02-10 07:44
I also have the same issue on Fedora 37 after having updated from 2.12 to 2.13.
I removed the cache and share files without any effect.

My log files are similary: when trying to start it stops without any error message after:
```
[08.02.2023 15:25:51.978] Debug: Maybe start at boot
[08.02.2023 15:25:51.978] Debug: We don't need to start at boot.
[08.02.2023 15:25:52.017] Debug: Writing the settings file
[08.02.2023 15:25:52.017] Debug: Write encrypted file
[08.02.2023 15:25:52.017] Debug: Incrementing nonce: 0
```

I do not know if related but on Android the app keeps the preferences but fails to restart/resume after leaving the airplane mode.

**Comment by data-sync-user** [comment] 2023-02-10 09:21
➤ Valentina Virlics commented:

Verified this on Ubuntu while using latest 2.13 build, and I am seeing the following:

  * Mozilla VPN automatically starts after device restart (Focal (20.04), Jammy (22.04))
  * App is not automatically put in foreground.

Also verified Linux Focal - KDE - and I am able to partially reproduce this as follows:

  * Mozilla VPN client is not shown at device restart, neither in background or foreground;
  * If opening the client user is logged in and the app gets turned ON automatically; (see below video from KDE)

!Screencast 2023-02-10 11_19_33.mp4|width=1920,height=1080!

**Comment by arnobl** [comment] 2023-02-11 09:43
Valentina, using a clean install or after an update from 2.12?

> App is not automatically put in foreground.
This never worked on Fedora. A different minor issue.

@JKingZapata Did you have the Qt issue that required not to use the latest qt 6.4 version?

**Comment by data-sync-user** [comment] 2023-02-13 12:19
➤ Valentina Virlics commented:

I’ve tried both after update and clean install. Same behavior as described below.

**Comment by arnobl** [comment] 2023-02-13 14:14
`ldd $(which mozillavpn) | awk '{print $1}' | while read n; do echo "----- $n ----"; dnf provides ^$n; donednf provides`

to show the packages vpn depends on on Fedora 37:
qt6-qtbase-6.3.1-4.fc37.i686
qt6-qtwebsockets-6.3.1-2.fc37.i686
qt6-qtbase-gui-6.3.1-4.fc37.i686
qt6-qtnetworkauth-6.3.1-2.fc37.i686
qt6-qtdeclarative-6.3.1-2.fc37.i686

I cannot use qt 6.4 because of an issue fixed in the main branch. May be due to that.
Other packages:

polkit-libs-121-4.fc37.i686
libblkid-2.38.1-1.fc37.i686
libXau-1.0.10-1.fc37.i686
libgpg-error-1.46-1.fc37.i686
libselinux-3.4-5.fc37.i686
libmount-2.38.1-1.fc37.i686
glib2-2.74.1-2.fc37.i686
glibc-2.36-9.fc37.i686
libgomp-12.2.1-4.fc37.i686
lz4-libs-1.9.4-1.fc37.i686
libzstd-1.5.2-3.fc37.i686
xz-libs-5.4.1-1.fc37.i686
libcap-2.48-5.fc37.i686
libicu-71.1-2.fc37.i686
libbrotli-1.0.9-9.fc37.i686
keyutils-libs-1.6.1-5.fc37.i686
krb5-libs-1.19.2-13.fc37.i686
libcom_err-1.46.5-3.fc37.i686
krb5-libs-1.19.2-13.fc37.i686
bzip2-libs-1.0.8-12.fc37.i686
graphite2-1.3.14-10.fc37.i686
libXext-1.3.4-9.fc37.i686
libxcb-1.13.1-10.fc37.i686
libxml2-2.10.3-2.fc37.i686
libglvnd-1:1.5.0-1.fc37.i686
pcre2-10.40-1.fc37.1.i686
pcre2-utf16-10.40-1.fc37.1.i686
libffi-3.4.4-1.fc37.i686
libgcrypt-1.10.1-4.fc37.i686
libb2-0.98.1-7.fc37.i686
double-conversion-3.1.5-7.fc37.i686
systemd-libs-251.7-611.fc37.i686
libicu-71.1-2.fc37.i686
freetype-2.12.1-3.fc37.i686
harfbuzz-5.2.0-1.fc37.i686
libpng-2:1.6.37-13.fc37.i686
libglvnd-opengl-1:1.5.0-1.fc37.i686
libglvnd-glx-1:1.5.0-1.fc37.i686
libxkbcommon-1.4.1-2.fc37.i686
libX11-1.8.4-1.fc37.i686
fontconfig-2.14.1-2.fc37.i686

**Comment by data-sync-user** [comment] 2023-02-16 06:49
➤ Magdalena Schwaighofer commented:

Set of logs from a user attached (vpn v2.13) Ubuntu 22.04

[^mozillavpn-2023-2-15_1.txt]

**Comment by data-sync-user** [comment] 2023-02-23 17:12
➤ Juan Zapata commented:

Support has received 20 user reports as of Feb 23

**Comment by data-sync-user** [comment] 2023-02-23 17:52
➤ Beatriz Rizental Machado commented:

Potentially related to https://mozilla-hub.atlassian.net/browse/VPN-3384 ( https://mozilla-hub.atlassian.net/browse/VPN-3384|smart-link ) . I have been able to reproduce this previously. I can check again tomorrow if I still can, if no one else picks it up while I am away.

**Comment by data-sync-user** [comment] 2023-02-24 14:28
➤ Valentina Virlics commented:

We did not reproduced this issue on VM (Kinetic and Jammy) because of what we thought that is a VM setting issue - https://mozilla-hub.atlassian.net/browse/VPN-4249 ( https://mozilla-hub.atlassian.net/browse/VPN-4249|smart-link ) .

We did not repro this issue on a physical machine - Linux Ubuntu - Focal - while using 2.13. 

As mentioned in below comments, after device restart if the “connect VPN at startup“ feature is enabled, app is automatically turned ON, but is not put in foreground (if i remember correctly this is something related to OS version) - using 2.14.0 (2.14.0~rc20230223153352-focal1) build.

**Comment by data-sync-user** [comment] 2023-03-06 14:34
➤ Santiago Andrigo commented:

.

**Closed by data-sync-user** 2023-03-06 14:34 UTC
Labels: bug

**Comment by data-sync-user** [comment] 2023-03-29 21:11
➤ Juan Zapata commented:

Adding a possible case still happening on 2.13. Made sure the user installed any pending system updates and tried resetting the VPN client through the developer options. In this particular case, user does not have the “connect on startup” setting enabled, however every time they restart their device they have to log back into the VPN. 

[^mozillavpn-2023-3-23-2.txt]
