### ISSUE TITLE
Old android browsers cannot load fxa links

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#814] opened 2021-04-07 17:32 UTC
Steps I use to reproduce:

-  In Android Studio create emulator for Android 5, 6, 7
-  Open emulator
-  Open default browser
-  Go to accounts.firefox.com
-  See blue spinning wheel (rather than login screen)

Same steps for Android 8 and 11 and accounts.firefox.com loads normally. I didn't bother testing the distros in between as I assume they're good.

**Comment by rbillings** [comment] 2021-04-07 18:38
Marking as minor as we do not support these Android versions.

**Comment by strseb** [comment] 2021-04-14 16:08
We're in the process of deprecating android 5,6. On 7 any real play-service enabled device should recive web-view updates so it _should_ not happen :)

**Closed by strseb** 2021-04-14 16:08 UTC
Labels: bug, qa_minor

**Comment by ValentinaPC** [comment] 2021-05-14 10:30
I was not able to reproduce this on my Android 6 (Huawei) device.
While loading accounts.firefox.com in Chrome/Opera or Firefox, I was able to sign in with success.
