### ISSUE TITLE
“mozillavpn linuxdaemon” error at Mozilla VPN start

### ISSUE THREAD

**Issue by AOiegas** [mozilla-mobile/mozilla-vpn-client#1196] opened 2021-06-14 15:29 UTC
#### Platforms affected:
- Linux Ubuntu 18.04 - [bionic build](https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/925690436);

#### Prerequisites:
- The VPN app is installed;

#### Steps to reproduce:
1. Open the VPN app;
2. Observe the results;

#### Expected result:
- The VPN app opens successfully;

#### Actual result:
- The VPN does not open and displays an error with the following text: “mozillavpn linuxdaemon needs to be updated or restarted.”;

#### Notes:
- On the focal build the VPN app can be started and the issue is not reproducing;
- Could not stop or find the daemon through the terminal;

![mzvpn](https://user-images.githubusercontent.com/85748693/121918152-733d5d80-cd3e-11eb-8d92-534b040d9c4c.png)

**Comment by bakulf** [comment] 2021-06-14 15:33
Owen, does it happen because the package is installed using `dpkg -i`?

**Comment by oskirby** [comment] 2021-06-14 16:21
As long as installation via `dpkg -i` reports success then it should identically to installation via `apt` or a PPA.

**Comment by bakulf** [comment] 2021-06-15 10:56
Can we have the logs of a bionic build?

**Comment by ValentinaPC** [comment] 2021-06-15 12:40
[mozillavpn.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6655588/mozillavpn.txt)
These are the only ones we could find. I see User Agent 2.3.0, and we installed the 2.3.1 build...

**Comment by oskirby** [comment] 2021-06-15 15:04
I've attempted to install the bionic packages using a fresh virtual machine and I can't seem to reproduce the error. There are a couple of things that we can check to see if the daemon was installed correctly.

To start off with, can you verify that the following files exist:
- `/usr/bin/mozillavpn` is the VPN executable
- `/usr/lib/systemd/system/mozillavpn.service` is the `systemd` file used to describe the daemon as a system service.
- `/usr/share/dbus-1/system-services/org.mozilla.vpn.dbus.service` enables the daemon as a bus-activatable service
- `/usr/share/dbus-1/systemd.d/org.mozilla.vpn.dbus.conf` configures the D-Bus access controls to reach the daemon

Assuming that is all good, then there are some commands we can use to check if the daemon is running:
- `sudo systemctl status mozillavpn` should list some information about the state of the daemon as seen by `systemd`
- `ps aux | grep mozillavpn` should list all processes that are running the VPN executable, this should include the daemon.
- `dbus-send --print-reply --system --dest=org.mozilla.vpn.dbus / org.mozilla.vpn.dbus.status` should connect to the daemon and print its status. If the daemon is not running, this will also start it.

If all else fails, you can manually start the daemon by running the command `sudo mozillavpn linuxdaemon` and see if that gets the client passed this error. If that works it should indicate that the problem is related to how the service is launched, and not any particular breakage in the daemon itself.

**Comment by oskirby** [comment] 2021-06-15 16:59
> [mozillavpn.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6655588/mozillavpn.txt)
> These are the only ones we could find. I see User Agent 2.3.0, and we installed the 2.3.1 build...

Looking through this log file, it seems that this was generated from a build on the main branch, since I am seeing messages related to the split tunnelling feature. Note that there is was a known bug in the 2.3.0 release which would cause prevent the daemon from generating logs (see https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1057).

Other places you might find logs would be `/home/$USER/.local/share/mozillavpn.txt` and possibly `/root/.local/share/mozillavpn.txt` if you started the daemon manually via `sudo`.

**Comment by oskirby** [comment] 2021-06-16 09:03
It seems that the daemon wasn't starting because it had gotten into the `masked` state  in systemd. Once a service becomes `masked` systemd will refuse to start the service when invoked over D-Bus, or by any other method. The problem can be worked around by issuing the command `sudo systemctl unmask mozillavpn` to get up and running again.

The question though, is how the service became masked. I suspect that it might have been caused by installing a package from the `main` branch and then downgrading to a 2.3.1 build. There was a change in the service file on the `main` branch which should configure the daemon to start on boot and the removal of that package may have left it masked when a downgrade occurs.

**Comment by AOiegas** [comment] 2021-06-16 11:36
Thanks @oskirby for your help. We've managed to start the VPN and now we were able to verify the unsecured network issue.

**Comment by bakulf** [comment] 2021-06-16 12:37
Closing the issue.

**Closed by bakulf** 2021-06-16 12:37 UTC
Labels: bug, linux, qa_normal

**Comment by data-sync-user** [comment] 2021-09-01 21:54
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been opened in error by the data sync.
