### ISSUE TITLE
Application content is displayed blurry on different scale

### ISSUE THREAD

**Issue by mariaberlinger** [mozilla-mobile/mozilla-vpn-client#1216] opened 2021-06-18 13:48 UTC
#### VPN version:
* 2.4.0 (2.202106162202)

#### Affected Platforms:
* Windows 10x64

#### Prerequisites:
* Have one FxA account with subscription.
* Have a second monitor connected with a different scale (e.g. 100%).

#### Steps to reproduce:
1. Open the VPN app.
1. Move the app on the second monitor.

#### Expected result:
* The app is displayed correctly.

#### Actual result:
* The app is displayed blurry.

#### Notes:
* See the attached screenshot.
* If the scale is different from 125%, the app is displayed blurry.
![stage-vpn](https://user-images.githubusercontent.com/54393305/122570926-e4d61e00-d054-11eb-81ee-ec2e6db45d5e.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-33)
┆Reporter: Data Sync

**Comment by data-sync-user** [comment] 2022-10-14 12:23
➤ Bianca Hidecuti commented:

Andrea Marchesini , this is still reproducing on Mozilla VPN 2.10.0 (2.202210111527), while on Windows 11.

!image_2022_10_14T12_20_07_545Z.png|width=442,height=425!

**Comment by data-sync-user** [comment] 2023-04-19 17:47
➤ Lesley Norton commented:

Bianca Hidecuti I cannot reproduce this. Can we close or are you still seeing this?

**Comment by data-sync-user** [comment] 2023-04-20 10:50
➤ Bianca Hidecuti commented:

Lesley Norton , Verified this on Mozilla VPN 2.15.0 (2.202304191607), using Windows 11 - scaling factor 100%, while being connected to a second monitor and I am still seeing some blurry content - for example, in tips and tricks screen - attaching a ss as well.

!image_2023_04_20T10_05_19_984Z.png|width=272,height=554!

Also, now while having the scaling factor set to 125% and using an external monitor, the whole app is blurry (not reproducing on the main monitor).

!image_2023_04_20T10_46_27_538Z.png|width=238,height=457!

!image_2023_04_20T10_46_40_520Z.png|width=255,height=463!

**Comment by data-sync-user** [comment] 2023-05-12 13:19
➤ Sarah Bird commented:

Believe already fixed.
Closed during bug squashing.

**Comment by data-sync-user** [comment] 2023-05-26 14:11
➤ Lesley Norton commented:

We are closing out low priority tickets that we don't have bandwidth to fix. Closed during bug squashing #2.

**Closed by data-sync-user** 2023-05-26 14:11 UTC
Labels: macos, windows, qa_minor
