### ISSUE TITLE
VPN 2.17 fails to launch on Ubuntu 20.04

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#8163] opened 2023-09-29 22:12 UTC
**Description**

Linux users (for now only reported on Ubuntu Focal) are unable to launch the VPN V2.17, either by clicking on the app icon or running mozillavpn from the Terminal. Running from Terminal prompts error `QDBusArgument: write from a read-only object` Uninstalling/reinstalling VPN does not resolve issue.

Does it impact functionality or aesthetics? Yes
Does this endanger users? What would be compromised and how likely is the threat? No
How annoying is this for affected users? (Think about how much 'in the way' this is, relative to what the user is trying to do) Yes
Does it degrade the user experience significantly? Very
Is it legally sensitive? No

**Centrality**
Core user journey

**Technical Information**

Platform: Ubuntu Focal 20.04
FX product: Mozilla VPN
Version 2.17

**Steps to Reproduce**

1. Install VPN using terminal commands
1. Attempt to launch VPN (either clicking on the app icon or using mozillavpn from the Terminal)

**Actual Results**

No VPN window opens and terminal shows error message

**Expected Results**

VPN client should open

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-5628)
┆Reporter: Juan Zapata

**Comment by rloutrel** [comment] 2023-09-30 09:15
Confirmed with Ubuntu Focal 20.04 here

**Comment by miniesta4** [comment] 2023-10-01 16:48
Confirmed.
5.15.0-84-generic #93~20.04.1-Ubuntu
Package: mozillavpn Version: 2.17.0-focal1

**Comment by edgarcheverier** [comment] 2023-10-02 08:32
I have the same problem with Ubuntu 20.04.6 LTS  Mozilla VPN Version 2.17, I tried uninstalling and installing again but after the update isn't working, it was working fine before the update.

**Comment by data-sync-user** [comment] 2023-10-02 16:14
➤ Santiago Andrigo commented:

Valentina Virlics Just curious - do you know why did this didn’t come up during regression testing?

**Comment by data-sync-user** [comment] 2023-10-02 16:19
➤ Naomi Kirby commented:

The error that causes the VPN to fail to start is:

[29.09.2023 14:25:44.414] Warning: QQmlApplicationEngine failed to load component
[29.09.2023 14:25:44.414] Warning: qrc:/ui/main.qml:12:1: module "components" is not installed (main.qml:12)
[29.09.2023 14:25:44.414] (CommandUI) Error: Failed to load  qrc:/ui/main.qmlI too am confused as to why we didn’t catch this during testing, but I will start digging into this ASAP.

**Comment by data-sync-user** [comment] 2023-10-03 06:33
➤ Valentina Virlics commented:

Santiago Andrigo Naomi Kirby 

We’ve updated the physical machine from Linux Focal (20.04) to Jammy (22.04), because it has more users (+Looker+ ( https://mozilla.cloud.looker.com/dashboards/428?Submission+Date=30+day&Client+Info+App+Channel=production&Client+Info+App+Display+Version=-%25%7E%25%2C-%25VersionName%25&Normalized+OS= ) source). We performed regression testing on Jammy and did some smoke on Lunar (23.04) and the newly Mantic (23.10). We covered 3 of 4 supported Linux versions.

In the regression week we do Windows 10 (alternate with 11), macOS 12 Intel (alternate with M1), Linux Jammy (some checks on Lunar), iOS 16 (some checks on 14), Android 13 ( some checks on 10/12). 

The +TestRail+ ( https://testrail.stage.mozaws.net/index.php?/plans/view/76211 ) runs also contain the version(s) we covered during regression.

Let us know if you have any other questions.

**Comment by nomad-software** [comment] 2023-10-05 18:45
I'm experiencing the same issue:
```
~ uname -a 
Linux home 5.15.0-84-generic #93~20.04.1-Ubuntu SMP Wed Sep 6 16:15:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
~ mozillavpn --version
mozillavpn 2.17.0
~ mozillavpn
QDBusArgument: write from a read-only object
```

**Comment by oskirby** [comment] 2023-10-06 16:33
I think I have bisected the problem down to dcd7365d77bc3b2f70ec6020af415576a4c04e19 it seems to be a problem with the QML cache generation.

**Comment by eugeneseppel** [comment] 2023-10-08 16:06
I have the same issue. Ubuntu 20.04

**Comment by dagobertstyle** [comment] 2023-10-11 17:41
Same issue here, on LinuxMint 20.2

**Comment by nomad-software** [comment] 2023-10-11 19:52
@data-sync-user is there any more updates on this please? This is a subscription service that people are paying for and should be fixed as soon as possible! Thanks.

**Comment by data-sync-user** [comment] 2023-10-13 10:55
➤ Magdalena Schwaighofer commented:

Update: we have 34 user reports so far

**Comment by same-k3k** [comment] 2023-10-13 11:36
same here

**Comment by data-sync-user** [comment] 2023-10-13 15:56
➤ Juan Zapata commented:

Updated to support medium due to increasing number of user reports

**Comment by nnadisic** [comment] 2023-10-16 09:37
Same issue here on Linux Mint 20.3

```
~ uname -a           
Linux xps13 5.15.0-84-generic #93~20.04.1-Ubuntu SMP Wed Sep 6 16:15:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

~ mozillavpn -v
mozillavpn 2.17.0

~ mozillavpn         
QDBusArgument: write from a read-only object
```

**Comment by data-sync-user** [comment] 2023-10-16 15:58
➤ Naomi Kirby commented:

I have been able to narrow the issue down to the version of cmake being used to build the project. Ubuntu 20.04 is stuck on version 3.16 which is why it was the only platform to encounter this issue. For whatever reason QML modules built on version 3.16 don’t seem to get their resource content registered correctly into the QRC namespace, and this causes the UI assets to fail to load.

**Comment by same-k3k** [comment] 2023-10-16 18:16
I build it accordingly to the instructions, and now it works. I wait now for the fix in the package.

**Comment by 42lax** [comment] 2023-10-17 22:12
`~$ uname -a 
Linux John-Lemur-Pro 6.0.12-76060012-generic #202212290932~1683754412~20.04~3254e87~dev-Ubuntu SMP PREEMPT_DY x86_64 x86_64 x86_64 GNU/Linux
~$ mozillavpn --version
mozillavpn 2.17.0
~$ mozillavpn
QDBusArgument: write from a read-only object`

Same issue.

**Comment by data-sync-user** [comment] 2023-10-19 08:48
➤ Valentina Virlics commented:

Verified this while using Mozilla VPN 2.18.0~build20231019-focal1 on a Focal VM. The app can be opened, but clicking the “Sign up” button, loads a white screen. 

Switching to Stage is not possible as the "Developer options” menu does not open.

Attaching a video.

!linuxfocal.mp4|width=498,height=800!

Naomi Kirby please let us know if we should reopen this ticket or track the new behavior in a new one. Thank you!

Attaching logs as well.

**Comment by data-sync-user** [comment] 2023-10-19 16:07
➤ Naomi Kirby commented:

Valentina Virlics could you upload logs from your attempt to sign up or open the developer menu with 2.18.0~build20231009~focal1? I am not able to reproduce the issues in my focal VM.

**Comment by data-sync-user** [comment] 2023-10-19 16:16
➤ Naomi Kirby commented:

Oh, wait, nevermind, I see the problem. Stand by for another fix.

**Comment by data-sync-user** [comment] 2023-10-19 21:19
➤ Naomi Kirby commented:

The latest issue should be fixed by PR #8337 ( https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8337 ) and should now be testable in main and releases/2.18.0

**Comment by Ukato** [comment] 2023-10-20 03:40
finally started investigating this issue as I'm having the same problem; on Focal here.  looks like I stumbled across this thread as the solution is about to be shipped out the door.  looking forward to the release so I don't have to build from scratch.

**Comment by data-sync-user** [comment] 2023-10-20 08:55
➤ Valentina Virlics commented:

Verified this as fixed on Linux Ubuntu 20.04 while using Mozilla VPN 2.18.0~rc20231019205659-focal1 build form release branch.

The client is installed with success. The “Developer options“ work.

Login is finalized with success and the Mozilla VPN can be turned ON.

!focal2.mp4|width=494,height=800!

**Closed** 2023-10-20 08:56 UTC

**Comment by Elias-Graf** [comment] 2024-08-28 15:39
I'm currently experiencing this on the latest version on NixOS:

```
❯ uname -a
Linux perseus 6.6.47 #1-NixOS SMP PREEMPT_DYNAMIC Mon Aug 19 04:04:32 UTC 2024 x86_64 GNU/Linux
❯ mozillavpn -v
mozillavpn 2.23.1
```

Is this a NixOS problem, or should I report it here?

**Comment by jddinneen** [comment] 2024-09-03 15:30
Also getting "QDBusArgument: write from a read-only object" on Manjaro (6.9.12-3) w/ mozillavpn 2.25.0.
