### ISSUE TITLE
Connection information chart flips

### ISSUE THREAD

**Issue by mariaberlinger** [mozilla-mobile/mozilla-vpn-client#1237] opened 2021-06-24 15:50 UTC
#### VPN version:
* 2.3.2 (2.202106231536);

#### Affected Platforms:
* Windows 10x64;
* macOS 11.4
* Ubuntu 18.04

#### Prerequisites:
* Have Mozilla VPN installed;
* Have one FxA account with subscription;
* Have the FxA subscribed account connected;

#### Steps to reproduce:
1. Connect to VPN;
1. Go to Connection Information and observe the network signal chart;

#### Expected result:
* The network chart is displayed correctly.

#### Actual result:
* The network chart jumps up and then down when opening the Connection Information panel.

#### Notes:
* See the attached screen record;
* This is reproducible for all the locations.
* Sometimes it doesn’t reproduce from the first try
![networkchart](https://user-images.githubusercontent.com/54393305/123293690-e2743800-d51c-11eb-812d-bfa37cf02b12.gif)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-27)

**Comment by data-sync-user** [comment] 2021-10-05 19:47
➤ Jessica Cook commented:

This issue seems resolved – suggesting to close this and mark as done – verified and looks to fixed on latest MacOS

**Comment by data-sync-user** [comment] 2021-10-06 12:57
➤ Maria Berlinger commented:

The issue still reproduces on latest build from main branch VPN 2.6.0 (2.202110060912) on Windows 10 and macOS 11.6. Please see attached video.

!CI chart.gif|width=359,height=569!

**Comment by data-sync-user** [comment] 2021-10-18 08:17
➤ Luminita Buruian commented:

Rebecca Billings Could you please help us figure out what the next steps for this issue should be?

It still reproduced last time we checked, but the issue is closed.

Thank you.

CC: Valentina Virlics

**Comment by data-sync-user** [comment] 2022-01-20 17:27
➤ Betty Fleming commented:

not applicable after the re-design

**Closed by data-sync-user** 2022-01-20 17:27 UTC
Labels: bug, UX, cross-platform, qa_minor
