### ISSUE TITLE
Multi-account container add-on and Firefox browser not detecting MozillaVPN is installed

### ISSUE THREAD

**Issue by suncoastkid** [mozilla-mobile/mozilla-vpn-client#8631] opened 2023-11-23 12:37 UTC
Unable to use MozillaVPN with Firefox browser and multi-account container add-on. Add-on and Firefox browser both do not detect MozillaVPN is installed and prompt user to install it.

Using 2.18.0 (2.18.0-jammy1) on Ubuntu 22.04.3 with Firefox 119.0.1 via Snap.

![2](https://github.com/mozilla-mobile/mozilla-vpn-client/assets/5851898/c5e87aa3-d78a-4c03-b66f-0e6764091a4e). 
![1](https://github.com/mozilla-mobile/mozilla-vpn-client/assets/5851898/f66d3cc3-f6e6-4556-b0e2-5b9fb4c428e2)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-5921)

**Comment by data-sync-user** [comment] 2023-11-23 13:55
➤ Bianca Hidecuti commented:

Hello!

Thank you for filling this. We are tracking the issue here: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/8318 ( https://github.com/mozilla-mobile/mozilla-vpn-client/issues/8318|smart-link )

**Comment by data-sync-user** [comment] 2023-12-11 17:12
➤ Adrienne Davenport commented:

Duplicate of VPN-2080.

**Closed by data-sync-user** 2023-12-11 17:12 UTC
Labels: bug

**Comment by data-sync-user** [comment] 2023-12-11 17:55
➤ Santiago Andrigo commented:

In the meantime, we are filing a request to update SUMO documentation for MAC: https://bugzilla.mozilla.org/show_bug.cgi?id=1869372 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1869372|smart-link )
