### ISSUE TITLE
Internet not working when Mozilla VPN is on

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1236] opened 2021-06-24 14:20 UTC
#### Affected versions:
* Mozilla VPN 2.3.2 (2.202106231537);

#### Affected Platforms:
* Windows 10;
* Linux;

#### Prerequisites:
* Have a FxA account and have an active subscription for Mozilla VPN;
* Have Mozilla VPN app installed on your device.

#### Steps to reproduce:
1. Open Mozilla VPN and login with the account from prerequisite;
1. Select a location and turn on the VPN;
1. Let the VPN running for 2-3 minutes;
1. Observe the VPN status in the activation screen and try to navigate on the internet.

#### Expected result:
* The screen displays the following text: “Secure and private” and the period of time since the VPN is running. The user is able to navigate on the internet.

#### Actual result:
* A “No Signal/Unstable - Check Connection” message is displayed and the user is not able to navigate on the internet. In some cases, the VPN activation screen is not changing, but the user is not able to navigate on the internet.

#### Notes:
* Reproducing constantly on WIndows, Linux, no matter of the selected location;
* Not reproducing on Mac OS;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-28)

**Comment by bakulf** [comment] 2021-06-24 14:38
We haven't changed the VPN layer. We have exactly the same code as 2.3 and 2.3.1. Could it be a mullvad issue? Do you see any better results in selecting a different server?

**Comment by madalincm** [comment] 2021-06-24 15:32
> We haven't changed the VPN layer. We have exactly the same code as 2.3 and 2.3.1. Could it be a mullvad issue? Do you see any better results in selecting a different server?

No. It is reproducible for different locations too. Could it be related to the following issue: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1215 ?

**Comment by oskirby** [comment] 2021-06-24 21:49
There were definitely some issues in the Windows implementation that could lead to connection instability, they they were specific to Windows. I don't suppose you would be able to share a log file with us to take a look at what's causing the connection problems?

**Comment by rbillings** [comment] 2021-07-07 16:30
Part of this may be fixed in 2.3.2. We need a log file that shows an attempt to connect.

**Comment by madalincm** [comment] 2021-07-08 11:45
Attached you can find the log file.
[mozillavpn-2021-7-8.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6784150/mozillavpn-2021-7-8.txt)

**Comment by oskirby** [comment] 2021-07-08 15:04
The attached log file appears to be showing the symptoms of two known issues that may be impacting the network performance:
- #1215 has been fixed and will be included in the 2.4.0 release (this is probably the root cause of your connection problems).
- #1225 is something that I am currently working on, and I hope to have it included in 2.4.0. You can mitigate it by either enabling local network access or disabling IPv6 in the network settings.

**Comment by madalincm** [comment] 2021-07-20 12:20
Verified as fixed on Mozilla VPN v. 2.4.0 (2.202107191712) on Windows 10. “No Signal/Unstable - Check Connection” message is no longer displayed on the activation screen and the navigation on the internet is possible.

**Comment by data-sync-user** [comment] 2021-08-13 18:54
➤ Pun Lam commented:

Rebecca Billings Nma-Sie-Anyene Davenport This is verified as fixed by QA. How will we handle this moving forward. Could the QA just close it or put in an recommendation to close it.

**Comment by rbillings** [comment] 2021-08-17 11:17
Closing this as verified.

**Closed by rbillings** 2021-08-17 11:17 UTC
Labels: bug, linux, windows, verified, qa_blocker
