### ISSUE TITLE
Duplicate devices showing in device list

### ISSUE THREAD

**Issue by jr-johnson-support** [mozilla-mobile/mozilla-vpn-client#963] opened 2021-05-04 20:42 UTC
Users are reporting after updating to 2.1.0 version they are seeing duplicate entries of devices added to the list of added devices and (i.e. 6 of 5 devices added)

**Expected Results**

After installing or reinstalling the VPN there should only be one entry of that device on the list.

**Actual Results**
- If the application is uninstalled and reinstalled on the same device, the device will duplicate in the device list. 
- alternately some users see 6 devices listed when they have only connected 5
[dupdevicelist.txt](https://github.com/mozilla-services/guardian-website/files/6423795/dupdevicelist.txt)

**Comment by bakulf** [comment] 2021-05-05 15:44
I'm unable to reproduce it. Does it work only when migrating from 1.4 to 2.x? Or in general?

**Comment by bakulf** [comment] 2021-05-05 15:45
@jr-johnson-support if you have more logs, it would be useful. Thank you!

**Comment by jr-johnson-support** [comment] 2021-05-05 21:59
[mozillavpn-2021-4-6.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6430467/mozillavpn-2021-4-6.txt)

only other set of logs I was able to find for users. Impacted. Most use the workaround of deleting devices manually.

**Comment by AOiegas** [comment] 2021-07-13 12:58
@bakulf  It seems this problem has resurfaced, or at leas something similar, and I don't understand what it's causing it. Reinstalling does not clear the duplicates. Currently seen on Windows 10, VPN build 2.4.0 (2.202107110548).
Attaching logs: 
[mozillavpn-2021-7-13.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6808976/mozillavpn-2021-7-13.txt)

![identical devices 1 1](https://user-images.githubusercontent.com/85748693/125455570-82152c5e-e9d0-461b-995e-3d14860a93c6.png)

**Comment by ValentinaPC** [comment] 2021-07-20 09:43
Closing this in favor of #1360

**Closed by ValentinaPC** 2021-07-20 09:43 UTC
Labels: p3, prod_bug, windows
