### ISSUE TITLE
Multi-Hop Front End

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#1436] opened 2021-07-27 19:45 UTC
┆Issue is synchronized with this [Jiraserver Task](https://mozilla-hub.atlassian.net/browse/VPN-733)

**Comment by lesleyjanenorton** [comment] 2021-08-20 19:44
Closing as dupe of #1581

**Closed** 2021-08-20 19:44 UTC
