### ISSUE TITLE
iOS in portrait mode only

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#2603] opened 2022-01-18 19:29 UTC
I use Mozilla VPN on an iPad that is almost always in landscape mode (with a keyboard).

Testflight build 940 for 2.7 is only showing in portrait mode.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1575)

**Comment by data-sync-user** [comment] 2022-01-19 09:58
➤ Valentina Virlics commented:

Hey, Sarah! The landscape mode was blocked while in VPN app, few months ago, for both iOS and Android.

Check out: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1539#issuecomment-899631214 ( https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1539#issuecomment-899631214|smart-link )  and https://github.com/mozilla-mobile/mozilla-vpn-client/pull/1100#issue-899819151 ( https://github.com/mozilla-mobile/mozilla-vpn-client/pull/1100#issue-899819151|smart-link ) .

**Comment by data-sync-user** [comment] 2022-01-21 22:11
➤ Sarah Bird commented:

I have landscape mode working on my ipad on version 2.6.2.

**Comment by data-sync-user** [comment] 2022-05-09 08:40
➤ Valentina Virlics commented:

Verified this on the last build from iOS, which is a 2.8.3 one, and the issue is still reproducing.

Moving this into blocked, until a build with the fix is available for testing.

**Comment by data-sync-user** [comment] 2022-05-09 09:47
➤ Andrea Marchesini commented:

Do you mean that the crash is still reproducible? Or the rotation does not work?

**Comment by data-sync-user** [comment] 2022-05-09 15:01
➤ Valentina Virlics commented:

I mean we do not yet have an 2.9 build on TestFlight to be able to check the fix.

**Comment by data-sync-user** [comment] 2022-05-24 15:15
➤ Lesley Norton commented:

Moving this back into QA since 2.9 testing on iOS should again be possible.

**Comment by data-sync-user** [comment] 2022-05-25 08:38
➤ Valentina Virlics commented:

Verified this on the last VPN 2.9.0 (2.202205250103) build wile using iOS 15 on my iPad Air 2.

Mozilla VPN app is displayed in landscape mode.

**Closed** 2022-05-25 08:38 UTC
