### ISSUE TITLE
Firefox has trouble loading different pages while VPN is on and the App Permission feature is enabled

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1403] opened 2021-07-22 13:58 UTC
#### VPN version:
2.4.0 (2.202107220713)

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
- Have one FxA account with subscription;
- Have the VPN installed on your machine;

#### Steps to reproduce:
1. Login to VPN with the account from prerequisites;
2. Go to Settings-> App Permissions;
3. Check the “Firefox” app;
4. Disable the App Permission feature;
5. Turn on the VPN;
6. Turn  OFF the VPN;
7. Enable App Permissions feature;
8. Turn ON VPN;
6. Load some gDocs using Firefox;

#### Expected result:
- The docs are loaded. Firefox has no issues while opening new pages in new tabs.

#### Actual result:
- Firefox is not working.

#### Notes:
- the pages that not work are different each time: github pages, gdoc pages, new tabs;
- Firefox starts working after uninstalling the VPN and restarting the browser;
- Not reproducing with Chrome;
[mozillavpn-2021-7-22.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6862726/mozillavpn-2021-7-22.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-779)

**Comment by strseb** [comment] 2021-07-23 11:06
I really cant reproduce this, with firefox 90 :(

**Comment by tcinotto** [comment] 2021-07-23 15:57
@chrisrooneys @jess-cook03 @peterbenvenuto Hi! We can't get new strings in time for 2.4 but @bakulf is going to let @jr-johnson-support know about this potential issue for users to put into sumo, but I'm thinking for 2.5 we should put some sort of messaging in the app, to recommend that users restart their apps. We can only see this with firefox but it could impact other things that we're not aware of.

**Comment by jess-cook03** [comment] 2021-07-28 16:49
@bfyee @peterbenvenuto lets see where this falls within scope for v2.5 or if its more v2.6 ---- can we consider this issue when we look at enhancements and other bugs for release planning?

**Comment by jess-cook03** [comment] 2021-08-11 20:04
@ValentinaPC is this still reproducible? 

Just trying to get a sense of severity with this and any needs from UX -- knowing string freeze is currently happening (Aug 18th cut off) and we would be looking at a quick inapp message using existing components to maybe address this. Which would need front end @lesleyjanenorton .
But is this something that needs a user facing fix? Maybe, maybe not depending on how many this will effect and how reproducible it is?

But if this is something that can happen in general to anyone when using the app permission feature and we want to make a generic "restart your app after changing this setting' then we could possibly?? 

Also cc @punster-moz if this will be priority for v2.5 or not?

**Comment by ValentinaPC** [comment] 2021-08-13 07:57
@jess-cook03 Yes, I am still blocked on different pages on Firefox browser, if I change the VPN status, while those pages are opened.

**Comment by bfyee** [comment] 2021-08-17 07:08
@ValentinaPC this is for an FxA account without a subscription as per above?  or is this if a live subscription gets cancelled and the user is still logged in?  i am trying to repro and of course can't access settings without a subscription.

**Comment by bfyee** [comment] 2021-08-17 07:20
i was able to repro this with a live subscription.  vpn on,  protect all apps "off",  firefox box checked to be excluded from VPN protection.   pages do not load.

**Comment by bfyee** [comment] 2021-08-17 07:41
https://drive.google.com/file/d/1jBAsLV04gVcHPae_OwbM-j55yparvXAx/view?usp=sharing  Here's a video

**Comment by ValentinaPC** [comment] 2021-08-18 13:24
@bfyee Yes, I mistyped the note from prerequisites - you need an account with subscription. Sry about that.

**Comment by data-sync-user** [comment] 2021-08-18 17:28
➤ Peter Benvenuto commented:

Designs for this issue are completed. You can find them in this figma file ( https://www.figma.com/file/k9gjzhdAisu1SHJwGX1U7j/Split-Tunneling_Settings?node-id=494%3A3404 ). If you have any questions please ping me. 

CC Brian Yee Basti (Sebastian) Streich

**Comment by data-sync-user** [comment] 2021-09-03 07:34
➤ Valentina Virlics commented:

Peter Benvenuto While adding your comment, the issue was closed. Is this intended? Is this fixed? Thanks!

**Comment by data-sync-user** [comment] 2021-09-03 11:53
➤ Basti (Sebastian) Streich commented:

Valentina Virlics  sorry, I marked this as “done” in Jira as the changes from the figma spec are now implemented 🙂

**Comment by data-sync-user** [comment] 2021-09-06 11:21
➤ Valentina Virlics commented:

This is still reproducing while using the last VPN 2.5.0/release build. Some of the pages from Firefox are not loaded if the VPN changes states. Browser restart is required.

**Comment by strseb** [comment] 2021-09-06 11:50
This is right, we did not change any of that :) - instead our "solution" is to have a help link on the bottom of the AppPermissions screen for now ( https://www.figma.com/file/k9gjzhdAisu1SHJwGX1U7j/Split-Tunneling_Settings?node-id=494%3A3404 ).

**Comment by data-sync-user** [comment] 2021-09-06 13:36
➤ Valentina Virlics commented:

Oh. Got it.

Verified this as fixed on the last VPN 2.5 build on Windows 10.

A “Learn more“ link was added for both enabled/disabled App permissions state.

Postfix screenshots.

!learnmore.png|width=218,height=358!

**Closed by data-sync-user** 2021-09-06 13:36 UTC
Labels: bug, windows, verified, UX, qa_normal, qa_minor
