### ISSUE TITLE
Unable to submit Support Ticket on Windows or Android

### ISSUE THREAD

**Issue by JC-Support** [mozilla-mobile/mozilla-vpn-client#1838] opened 2021-09-17 19:53 UTC
I am unable to submit a support ticket while logged in on both Android and Windows. 

[JCuevas_Windowslogs_2.5.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/7188147/JCuevas_Windowslogs_2.5.txt)
[JCuevas_Androidlogs_2.5.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/7188152/JCuevas_Androidlogs_2.5.txt)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1024)

**Comment by data-sync-user** [comment] 2021-09-22 16:36
➤ Joseph Anthony Cuevas commented:

Have not seen any other issues with this or customer reports as of 9/22/2021. Safe to close and we can reopen if there are any new issues.

**Comment by data-sync-user** [comment] 2021-09-22 16:48
➤ Rebecca Billings commented:

Unreproducible

**Comment by lesleyjanenorton** [comment] 2022-07-22 23:53
Closing since it looks like this is no longer reproducible

**Closed by lesleyjanenorton** 2022-07-22 23:53 UTC
