### ISSUE TITLE
Feedback form in app

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#909] opened 2021-04-28 09:31 UTC
The VPN client should have a Feedback form in app to submit, together with the user's feedback, logs, version number, platform, arch, and any extra info useful for debugging.

@jess-cook03 can we work together to "draw" this form? The UX/UI of it?

**Comment by jess-cook03** [comment] 2021-04-30 14:43
Large sized UX item
cc Diana Horn

**Comment by jess-cook03** [comment] 2021-05-04 15:50
Update after design checkin 4/4:
Design to assess feasibility and commitment and circle back with team to understand priority for this release.

**Comment by jess-cook03** [comment] 2021-05-06 14:10
Update after team planning session for v2.3 -- agreed to move to v2.4 to allow for time to develop further.
Needs content, design and further understanding of tech implementation.

**Comment by mfrydr** [comment] 2021-06-04 14:10
I would love to submit info about websites that don't work well while the VPN is running (e.g. replit.com)

**Comment by peterbenvenuto** [comment] 2021-06-09 14:52
Update after 2.4 feature deep dive -- 2 phase solution was discussed. Phase 1: X-platform design solution will be implemented for 2.4. Phase 2: App Store Review screen will be added as a stretch goal, but potentially pushed to 2.5. Designs for Phase 2 completed in this [figma file](https://www.figma.com/file/nPn8jQUlIrhVTqh48wm7UK/In-App-Feedback-Form?node-id=149%3A0).

**Comment by jess-cook03** [comment] 2021-06-25 15:08
✅ designs have been completed and delivered for this ticket/feature for v2.4 and v2.5
cc @peterbenvenuto

**Comment by lesleyjanenorton** [comment] 2021-07-08 22:15
Closing - this is done!

**Closed by lesleyjanenorton** 2021-07-08 22:15 UTC
Labels: UX, cross-platform, needs-content, p2

**Comment by ValentinaPC** [comment] 2021-07-20 10:57
Verified this cross-platform on the last 2.4.0 VPN builds.
The In App Feedback feature was implemented and has no major issues. Some issues were logged separately.
Marking this as verified.

**Comment by data-sync-user** [comment] 2021-08-06 23:41
➤ Nma-Sie-Anyene Davenport commented:

Duplicate of VPN-216
